
export const CSV_DATA = `ID,Venue,Google Location URL,IMAGE,MENU,Contact Number,POC PHONE,POC EMAIL,Type,Location,Commission,Family Friendly,Cuisine,Opening Hours,Availability,Normal DayPrice per person,"Venue,Signature/Busiest Day",Promo Venue,Signature dish,"Venue,High Traffic Area",Loud 1/10,Romantic Score 1-10,Party Vibe 1-5,Instagrammable 1-5,"Venue,Sunset View",Indoor Outdoor,Business friendly,"Venue,Dress Code","Venue,Birthday Venue","Venue,USP",Signature dish + extra details,
1,Sirene,https://maps.app.goo.gl/YpJjZhHtNL462Ekf6,https://drive.google.com/file/d/13ll1BoosiRezdRQHgZaRHTk0IsuPBjNe/view?usp=sharing,https://drive.google.com/file/d/1YcjqJtGbUzZct-FC8R2fGMCENU0gR4S3/view?usp=sharing,048340303,,,Restaurant,Jumeirah 1,0%,,Greek,12:00 - 02:00,All opening hours,1000,"Sirene,Saturday",,"Sirene,""Seafood Linguine | Grilled Octopus""","Sirene,No",8,8,8,10,"Sirene,Yes","Sirene,Outdoor","Sirene,No","Sirene,Beach Chic","Sirene,Yes","Sirene,""Luxury beach dining""","Sirene Beach by GAIA,https://www.zomato.com/dubai/sirene-beach-by-gaia-jumeirah-1/menu,Greek Mediterranean,Greek mezze; taramasalata; grilled octopus,Fresh whole fish; seafood pasta; grilled lamb chops,Mediterranean spritz; rosé wines,Fresh fish & Greek mezze,350–500,Seafood; Vegetarian options,Upscale Greek beach dining; menu not fully public",
2,Summersalt,https://maps.app.goo.gl/XMN3NPTvbsDTiitC7,https://drive.google.com/file/d/1SI3DeFL3LLQ-5iVu1KvOfqFo4SvCepI7/view?usp=sharing,https://drive.google.com/file/d/1irGQY0WitLcoOEKn5jYEoDDu6Y-aoCGE/view?usp=sharing,,,,Restaurant,Mina Salam,,,Mediterranean,12:00 - 02:00,All opening hours,500,"Summersalt,Saturday",,"Summersalt,""Lobster Thermidor | Sea Bream Harra""","Summersalt,Yes",6,9,5,8,"Summersalt,Yes","Summersalt,Outdoor","Summersalt,Yes","Summersalt,Beach Chic","Summersalt,Yes","Summersalt,""Upscale beachfront with Burj views""","Summersalt,https://www.jumeirah.com/en/stay/dubai/jumeirah-al-naseem/dining/al-naseem-summersalt,Latin Mediterranean,Seafood tacos; ceviche; salads,Grilled fish; premium steaks; seafood platters,Signature margaritas; beach cocktails,Seafood & ceviche,300–500,Seafood; Vegetarian; GF options,Beach club + restaurant menu; relaxed luxury",
3,Shimmers,https://maps.app.goo.gl/qwuZvNvKZkYcdySV7,https://drive.google.com/file/d/1HLF1z9km5vVSLx9WVqA3Yltq6exeUN-t/view?usp=sharing,https://drive.google.com/file/d/1lVYrRNrJ_oOZB1Aa6jS0farwtUsUsOaE/view?usp=sharing,,,,Restaurant,Al Naseem,,,Mediterranean,12:00 - 02:00,All opening hours,500,"Shimmers,Saturday",,"Shimmers,""Greek Sea Bass | Lamb Souvlaki""","Shimmers,Yes",6,8,5,8,"Shimmers,Yes","Shimmers,Outdoor","Shimmers,Yes","Shimmers,Beach Chic","Shimmers,Yes","Shimmers,""Authentic Greek beach vibes""","Shimmers,Google Maps listing,Mediterranean Greek,Greek salads; calamari; mezze,Grilled seabass; lamb chops; pasta,Wine; classic cocktails,Grilled fish & mezze,250–400,Seafood; Vegetarian,Classic Greek beach restaurant; menu varies seasonally",
4,African Queen,https://maps.app.goo.gl/1NXsDbnr5Dy7rQJJA,https://drive.google.com/file/d/1mnImiP66L21if5zG8TZx3RtNjRx6eqUs/view?usp=share_link,https://drive.google.com/file/d/12StcURwz0scxELX8T0UqQZGE4Cu6pmI0/view?usp=sharing,045154600,,,Restaurant,Jumeirah 1,10%,Yes,Mediterranean,12:00 - 02:00,All opening hours,500,"African Queen,Friday",25%,"African Queen,""Moroccan Lamb Tagine | Harira Soup""","African Queen,No",6,6,5,6,"African Queen,yes","African Queen,Indoor","African Queen,No","African Queen,Casual","African Queen,No","African Queen,""Moroccan home-style comfort""","African Queen,https://africanqueen-restaurant.com/Dubai/AFRICAN-QUEEN_DUBAI_menu.pdf,French Riviera Mediterranean,Burrata; beef carpaccio; Niçoise salad,Lobster pasta; grilled seabass; lamb cutlets,French wines; classic cocktails,Lobster pasta & burrata,350–550,Seafood; Vegetarian,Full PDF menu available",
5,Baoli,https://maps.app.goo.gl/PKVGGgD7Vr7XMv7X9,https://drive.google.com/file/d/102AdBOiDt_qPLYw58P4ogxKkKL0sLVrz/view?usp=sharing,https://drive.google.com/file/d/15-tg7JmmImnqZE0KMNpIQgpFdYSFxLwm/view?usp=sharing,044915500,,,Restaurant,Jumeirah 1,"10% - Weekdays: no min, Weekends - min 5K",Yes early seating (6+ weekdays),French Mediterranean,12:00 - 02:00,All opening hours,1000,"Baoli,Saturday",,"Baoli,""Black Cod Caramel | Crispy Duck Salad""","Baoli,Yes",9,7,9,8,"Baoli,yes","Baoli,Both","Baoli,No","Baoli,Smart Elegant","Baoli,Yes","Baoli,""High-energy Asian glamour""","Baoli,https://baoli-restaurant.com/img/menus/Baoli-Restaurant-Menu.pdf,French Mediterranean & Asian Fusion,Sushi; sashimi; tempura lobster,Wagyu beef; robata seafood; pasta,Signature cocktails; champagne,Wagyu & sushi,450–650,Seafood; Vegetarian; GF options,Dinner-to-party venue",
6,BCH:CLB,https://maps.app.goo.gl/9K2i4MUmJamRB5nL8,https://drive.google.com/file/d/1CcUMtlmun9LvgWus7jMwu9b8_YL7KSbC/view?usp=sharing,https://drive.google.com/file/d/1Lk7h_xLtDrhpWDUlWocL5ruuyF2Arrjh/view?usp=sharing,048343803,,,Restaurant,Palm Jumeirah,10%,No,Mediterranean,12:00 - 02:00,All opening hours,500,"BCH:CLB,Saturday",,"BCH:CLB,""Tuna Tataki | Wagyu Beef Sliders""","BCH:CLB,Yes",9,5,9,6,"BCH:CLB,Yes","BCH:CLB,Both","BCH:CLB,No","BCH:CLB,Beach Chic","BCH:CLB,Yes","BCH:CLB,""Trendy beach club scene""","BCH:CLB,Instagram / venue request,International Beach Club,Sushi rolls; sharing platters,Grilled seafood; premium mains,High-energy cocktails,Sushi & sharing boards,300–500,Seafood; Vegetarian,Menu not publicly listed; party-focused",
7,Casa Amor,https://maps.app.goo.gl/zLqoXZfihZRzyduj6,https://drive.google.com/file/d/1OUFHgwmzUS-hbjQus0-eKmH9lV9e2pPy/view?usp=sharing,https://drive.google.com/file/d/1KTQbqhYYKEZUIUlc-Bpc6KM27f0AxqRS/view?usp=sharing,047772223,,,Restaurant,Jumeirah 1,10%,Yes early seating,French,12:00 - 02:00,All opening hours,1000,"Casa Amor,Saturday",25%,"Casa Amor,""Truffle Pizza | Grilled King Prawns""","Casa Amor,Yes",9,7,8,8,"Casa Amor,Yes","Casa Amor,Outdoor","Casa Amor,No","Casa Amor,Beach Chic","Casa Amor,Yes","Casa Amor,""French Riviera beach experience""","Casa Amor,Instagram / venue request,Mediterranean Riviera,Salads; burrata; light seafood,Grilled meats; fish; pasta,Classic cocktails; rosé,Beach sharing plates,300–450,Vegetarian; Seafood,Relaxed Riviera beach dining",
8,Eva,https://maps.app.goo.gl/Bs1KCEuKkAy58kDp8,https://drive.google.com/file/d/1mjw_c-3T-XdJ6VJHhfZUZ0cDlSORwJ98/view?usp=sharing,https://drive.google.com/file/d/1WgjOqMT0L_LUL0UO5CISZWcv0e9N-r_b/view?usp=sharing,045104800,,,Restaurant,Palm Jumeirah,5%,Yes early seating,Mediterranean,12:00 - 02:00,All opening hours,500,"Eva,Saturday",,"Eva,""Mediterranean Sea Bass | Lamb Chops""","Eva,Yes",7,7,6,6,"Eva,Yes","Eva,Outdoor","Eva,No","Eva,Beach Chic","Eva,Yes","Eva,""Mediterranean boho beach vibe""","Eva,Instagram / venue request,European Mediterranean,Light starters; salads,Grilled fish; pasta,Wine & cocktails,Seafood mains,300–450,Vegetarian; Seafood,Lifestyle beach venue",
9,Gigi,https://maps.app.goo.gl/37F7Zx6cQEc9rP4a7,https://drive.google.com/file/d/1eZXgPvFz7bO_vIqmVhRx25_PdZdpjZd-/view?usp=sharing,https://drive.google.com/file/d/1T-Ak5QIrEKPzEsNl7W-rgGYMI6tOzMlt/view?usp=sharing,044983900,,,Restaurant,Jumeirah 1,10%,Yes early seating,Italian,12:00 - 02:00,All opening hours,500,"Gigi,Saturday",,"Gigi,""King Crab Salad | Truffle Pasta""","Gigi,Yes",8,7,6,7,"Gigi,Yes","Gigi,Outdoor","Gigi,No","Gigi,Beach Chic","Gigi,Yes","Gigi,""Chic French beach lifestyle""","Gigi,Instagram / venue request,Italian Mediterranean,Antipasti; burrata; salads,Pasta; pizza; seafood,Italian wines; spritz,Pasta & burrata,300–450,Vegetarian; Seafood,Italian beach lifestyle",
10,Gitano,https://maps.app.goo.gl/EyBRbrpBM1NkhAB77,https://drive.google.com/file/d/1fWB2jdmxeI1x_i69xGYNmi7kPtmmtyjc/view?usp=sharing,https://drive.google.com/file/d/1n9vCzGykR-UdGq6ANx83ZPFcorrIeNLG/view?usp=sharing,0585662320,,,Restaurant,Jumeirah 1,10% above 500 AED,Yes early seating,Mexican,12:00 - 02:00,All opening hours,500,"Gitano,Saturday",25%,"Gitano,""Tuna Tostada | Charcoal Grilled Chicken""","Gitano,Yes",7,7,6,8,"Gitano,Yes","Gitano,Outdoor","Gitano,No","Gitano,Beach Chic","Gitano,Yes","Gitano,""Mexican jungle-inspired beach club""","Gitano,Instagram / venue request,Modern Mexican Latin,Ceviche; guacamole; tacos,Grilled meats; seafood platters,Mezcal cocktails; margaritas,Tacos & ceviche,300–500,Seafood; GF options,Jungle-style Mexican beach venue",
11,Maison De La Page,https://maps.app.goo.gl/yme9uVQNJYHVUV7t7,https://drive.google.com/file/d/1qLMQtm72ONVUpp8Lmx38L9UCgLTQywKa/view?usp=sharing,https://drive.google.com/file/d/1NpxgD6s2kOGo3vHi4W1n7EFoTn5BXjN6/view?usp=sharing,044559989,,,Restaurant,Palm Jumeirah,5% below 5K and 8% above 5K net,Yes,French Mediterranean,12:00 - 02:00,All opening hours,500,"Maison De La Page,Saturday",,"Maison De La Page,""Lobster Tagliatelle | Beef Tartare""","Maison De La Page,Yes",6,7,6,7,"Maison De La Page,Yes","Maison De La Page,Outdoor","Maison De La Page,Yes","Maison De La Page,Beach Chic","Maison De La Page,Yes","Maison De La Page,""Elegant Mediterranean beachfront""","Maison De La Page,https://www.westbeach.ae/en/club/maison-de-la-plage,French Mediterranean,Seafood starters; salads,Grilled fish; premium mains,Wine; champagne,Seafood & French classics,350–550,Seafood; Vegetarian,Elegant beachfront dining",
12,Ninive beach,https://maps.app.goo.gl/K4FRHB7KsyN35Crk6,https://drive.google.com/file/d/1J9Nzf2b72VpMHHTReH6PIJQtYL1HRFWC/view?usp=sharing,https://drive.google.com/file/d/1PPMUYJTZmM71FWHjYx6Kwlry0rggMuat/view?usp=sharing,044984200,,,Restaurant,Jumeirah 1,10%,No,Middle Eastern,12:00 - 02:00,All opening hours,500,"Ninive beach,Saturday",,"Ninive Beach,""Moroccan Mezze | Lamb Shoulder""","Ninive beach,Yes",6,5,6,5,"Ninive beach,Yes","Ninive beach,Outdoor","Ninive beach,Yes","Ninive beach,Beach Chic","Ninive beach,Yes","Ninive beach,""Arabian coastal lounge""","Ninive Beach,https://ninivebeach.ae/wp-content/uploads/2024/12/Ninive_Pool_Menu.pdf,Middle Eastern & Mediterranean,Wagyu kibbeh; halloumi; fattoush,Grilled prawns; wagyu steak; seafood skewers,Signature Middle Eastern cocktails,Wagyu & grills,300–450,Halal; Vegetarian; Seafood,Arabian coastal dining",
13,O Beach,https://maps.app.goo.gl/2jSGedv1VUPSN6HQ9,https://drive.google.com/file/d/1ouwDClXUD9eOAjvd9mvQzjdYCdK5CUKF/view?usp=sharing,https://drive.google.com/file/d/1ng2Ye9MlKfwfZzJW65TGDIPLxlGEO51E/view?usp=sharing,0528580464,,,Restaurant,Dubai Marina,10%,No,Party Dining,12:00 - 02:00,All opening hours,200,"O Beach,Saturday",,"O Beach,""Chicken Skewers | Sushi Platters""","O Beach,Yes",9,5,9,5,"O Beach,Yes","O Beach,Outdoor","O Beach,No","O Beach,Beach Club Glam","O Beach,Yes","O Beach,""Party-focused day club""","O Beach Dubai,https://obeachdubai.com/restaurant,Asian Mediterranean Fusion,Sushi; raw bar; salads,Grilled meats; seafood; vegetarian bowls,Signature party cocktails,Sushi & seafood,350–550,Vegetarian; Seafood; GF options,Party-focused day club",
14,Playa,https://maps.app.goo.gl/2SavdpDEUJX34S7q7,https://drive.google.com/file/d/14pnpvJDfey5jdSb3dMrUWRkDj-jEQQAz/view?usp=sharing,https://drive.google.com/file/d/1ztYzVDbkAYFDY3juIeIn2v702TYO4RYX/view?usp=sharing,80075292,,,Restaurant,FIVE Luxe,10%,Yes early,Peruvian,12:00 - 02:00,All opening hours,500,"Playa,Saturday",25%,"Playa,""Seafood Ceviche | Grilled Tiger Prawns""","Playa,Yes",10,5,10,5,"Playa,Yes","Playa,Outdoor","Playa,No","Playa,Beach Chic","Playa,Yes","Playa,""Latin sunset party vibes""","Playa,Instagram / venue request,Peruvian Beach Club,Seafood starters; sharing plates,Grilled fish; meats; pasta,Classic beach cocktails,Sharing seafood,300–450,Vegetarian; Seafood,Latin sunset vibes",
15,Surf Club,https://maps.app.goo.gl/Xh2LbxkjQGot1Wwr7,https://drive.google.com/file/d/12LMN2bCCWujQMiaKkkBG-HX1zLjFbWBd/view?usp=sharing,https://drive.google.com/file/d/1jQ5-GqEnzN0lTIIA3AWk-8A05kox8VI8/view?usp=sharing,045895444,,,Restaurant,Palm Jumeirah,10%,Yes early seating,Mediterranean,12:00 - 02:00,All opening hours,500,"Surf Club,Saturday",,"Surf Club,""Salt-Baked Sea Bass | Lobster Pasta""","Surf Club,Yes",10,5,10,7,"Surf Club,Yes","Surf Club,Outdoor","Surf Club,No","Surf Club,Beach Chic","Surf Club,Yes","Surf Club,""Premium seaside dining""","Surf Club,https://www.surfclubdubai.com/menus,Mediterranean Coastal,Raw bar; tapas; sushi,Grilled fish; seafood platters; mains,Citrus spritz; coastal cocktails,Raw bar & grilled fish,300–500,Seafood; Vegetarian,Premium seaside vibes",
16,Verde Beach,https://maps.app.goo.gl/CikD3bhTBPjGUYxd7,https://drive.google.com/file/d/1SMhjOil7Fy4jCf39rlS2T9CwIqnfmQr1/view?usp=sharing,https://drive.google.com/file/d/1sR_fctu_JFjEo41qa9rpjNtecakzGCUe/view?usp=sharing,042285053,,,Restaurant,JBH,10%,Yes 10+,Mediterranean,12:00 - 02:00,All opening hours,500,"Verde Beach,Saturday",,Spicy guacamole (Verde signature) | Timeless pizza with truffle | Grilled octopus (warm sumac potatoes),"Verde Beach,Yes",8,5,9,8,"Verde Beach,Yes","Verde Beach,Outdoor","Verde Beach,Yes","Verde Beach,Beach Chic","Verde Beach,Yes","Verde Beach,""French luxury beach experience""","Verde Beach,Instagram / venue request,Mediterranean Beach Club & Lounge,Fresh seafood salads; mezze platters,Grilled seabass; premium steak; pasta,Citrus spritz; rosé; classic cocktails,Seafood sharing platters,350–550,Seafood; Vegetarian; GF options,French luxury beach",
17,Nammos,https://maps.app.goo.gl/RtS8FsZi2hXJmYAg8,https://drive.google.com/file/d/1n6bbqpNU2kh5Kb0yLCuqic5cbjF2wY9m/view?usp=sharing,https://drive.google.com/file/d/1ez-D-wQ95o1tJk6HAUbJiQq8rYmef0gj/view?usp=sharing,0581210000,,,Restaurant,Jumeirah Beach,10%,Yes early seating,Mediterranean and Asian,12:00 - 02:00,All opening hours,1000,"Nammos,Saturday",25%,Spicy Tuna on spider roll & soft-shell crab (Nammos Signatures) | Salmon Teriyaki on shrimp tempura roll (Nammos Signatures) | Baked Spicy Crab Maki (Nammos Signatures) | All‑time Classic Nammos Chocolate Mousse,"Nammos,Yes",8,7,9,9,"Nammos,Yes","Nammos,Outdoor","Nammos,Yes","Nammos,Beach Elegant","Nammos,Yes","Nammos,""Mykonos luxury lifestyle""","Nammos,https://nammosdxb.com/menus,Mykonos-style Mediterranean,Greek mezze; oysters; burrata,Whole grilled fish; lamb chops; pasta,Signature Mykonos cocktails,Oysters & grilled fish,450–800,Seafood; Vegetarian options,Mykonos-inspired beach dining",
18,Sakhalin,https://maps.app.goo.gl/V3newDyu9tdWtvvZ6,https://drive.google.com/file/d/1sCOjV4u8gN5xlHTMHjQGEGaNVBjr-hhj/view?usp=sharing,https://drive.google.com/file/d/1ciiPIGYlxx2TLvhtGkNZwmWgJkw7nsyG/view?usp=sharing,044951600,,,Restaurant,Jumeirah 1,5%,Yes early seating,"Mediterranean, Asian, and Russian",12:00 - 02:00,All opening hours,1000,"Sakhalin,Friday",,"Sakhalin salad with Kamchatka crab, avocado & rouille | King crab catalana style | Roll Sakhalin (Kamchatka crab, salmon, red caviar) | Signature lobster roll","Sakhalin,Yes",7,5,6,7,"Sakhalin,Yes","Sakhalin,Indoor","Sakhalin,Yes","Sakhalin,Smart Elegant","Sakhalin,Yes","Sakhalin,""High-end seafood gastronomy""","Sakhalin,Instagram / venue request,Pan-Seafood & Luxury Seafood Grill,Caviar; king crab salad; sashimi,Grilled king crab; lobster tempura; seafood towers,Champagne; seafood cocktails,King crab & seafood tower,600–1000,Seafood; GF options,Premium seafood grill",
19,Bar du port,https://maps.app.goo.gl/XFZUWCmzL5cwT7du7,https://drive.google.com/file/d/1zPNd7_qtjk7ko8upEiLa7LM61rBoZpvE/view?usp=sharing,https://drive.google.com/file/d/1fgdjwqSo-InCodGuh_cNCQbcLDTycb74/view?usp=sharing,043324868,,,Restaurant,Marina,,,french,12:00 - 02:00,All opening hours,1000,"Bar du port,Friday",,"Lobster Linguine, Tuna Tartare, grilled Sea Bass","Bar du port,Yes",7,5,8,7,"Bar du port,Yes","Bar du port,Outdoor","Bar du port,Yes","Bar du port,Smart Casual","Bar du port,Yes","Bar du port,""Mediterranean marina hotspot""","Bar du Port,Instagram / venue request,Mediterranean Marina Dining,Seafood starters; burrata; salads,Grilled fish; lamb chops; pasta,Classic cocktails; rosé; wine,Seafood & Mediterranean mains,300–500,Seafood; Vegetarian,Marina Mediterranean hotspot",
20,Zeta 77,https://maps.app.goo.gl/F9TPT2L2An6WJyfP8,https://drive.google.com/file/d/1rnSb0QFGMlcgJCNXhyDSZQl95F3gzely/view?usp=sharing,https://drive.google.com/file/d/1AzcZDER6oQuPtZ6I45VncXKbo0wmtvye/view?usp=sharing,048798866,,,Restaurant,JBR,10%,No,Asain,12:00 - 02:00,All opening hours,500,"Zeta 77,Saturday",25%,"Zeta 77,""Wagyu Tataki | Truffle Tuna Tartare""","Zeta 77,Yes",7,7,8,6,"Zeta 77,Yes","Zeta 77,Outdoor","Zeta 77,Yes","Zeta 77,Smart Casual","Zeta 77,Yes","Zeta 77,""Sky-high poolside dining""","Zeta 77,Instagram / venue request,Sky Pool Dining & Lounge,Light starters; salads,Grilled seafood; premium mains,Signature cocktails; champagne,Seafood & mains,400–700,Seafood; Vegetarian,Rooftop sky pool dining",
21,Aura Skypool,https://maps.app.goo.gl/Ft7iEoXUfJGPitZu8,https://drive.google.com/file/d/1bWiWvQ7U9xE9Mn4xNX7BgQ1Ac-6EJAnl/view?usp=sharing,https://drive.google.com/file/d/1vhdDLlIX0rxBBEX4cSUiKRXnrW6Rptys/view?usp=sharing,045662121,,,Restaurant,Palm Jumeirah,,,mediterranean,12:00 - 02:00,All opening hours,1000,"Aura Skypool,Saturday",,"Aura Skypool,""Sushi Samba Roll | Crispy Calamari""","Aura Skypool,Yes",7,9,6,10,"Aura Skypool,Yes","Aura Skypool,Outdoor","Aura Skypool,No","Aura Skypool,Resort Chic","Aura Skypool,Yes","Aura Skypool,""360° infinity pool experience""","Aura Skypool,https://auraskypool.com/menus,International Poolside Fine Dining,Light bites; salads; seafood starters,Premium mains; grilled fish; steaks,Signature cocktails; champagne,Poolside seafood & mains,450–800,Seafood; Vegetarian; GF options,Highest 360° sky pool",
22,Adaline,https://maps.app.goo.gl/GmW9t3aYCTFdUJGG9,https://drive.google.com/file/d/1QrkeMJGuZoI4iWqrzHixK7MdLV83BqC6/view?usp=share_link,https://drive.google.com/file/d/1NgUQCocYNGh_-0Fd-nF6sWMTj3Q7tCEZ/view?usp=sharing,044986200,,,Restaurant,DIFC,10%,No,Italian,12:00 - 02:00,All opening hours,500,"Adaline,Friday",,"Adaline,""Truffle Burrata | Wagyu Beef Sliders""","Adaline,Yes",8,8,9,7,"Adaline,No","Adaline,Indoor","Adaline,Yes","Adaline,Smart Casual","Adaline,No","Adaline,""Refined modern dining""","Adaline,Instagram / venue request,Modern Italian Fine Dining,Seasonal starters; burrata; crudo,Premium grilled meats; seafood; pasta,Crafted cocktails; fine wines,Seasonal mains & seafood,350–550,Vegetarian; Seafood; GF options,Refined Italian dining",
23,Alaya,https://maps.app.goo.gl/pWhdk4ayS6TdpMFGA,https://drive.google.com/file/d/1tE3in8Un073YJrRxIkupaTsuUKd0PluW/view?usp=sharing,https://drive.google.com/file/d/1u_qBnSWTCPZEciHEwHQ7Vu9tPVBRf95t/view?usp=sharing,045706289,,,Restaurant,DIFC,10%,Yes early seating,Middle Eastern,12:00 - 02:00,All opening hours,500,"Alaya,Friday",25%,"Alaya,""Spiced Lamb Ribs | Sea Bream Sayadieh""","Alaya,Yes",8,6,8,6,"Alaya,No","Alaya,Indoor","Alaya,Yes","Alaya,Smart Elegant","Alaya,No","Alaya,""Middle Eastern Mediterranean luxury""","Alaya,Instagram / venue request,Middle Eastern Mediterranean Luxury,Hot & cold mezze; truffle hummus,Grilled lamb; seafood; signature rice dishes,Middle Eastern cocktails; wine,Mezze & lamb dishes,400–650,Halal; Vegetarian; Seafood,Levantine Mediterranean luxury",
24,Gaia,https://maps.app.goo.gl/ttndvumyKoAmdXFB9,https://drive.google.com/file/d/1Jb3PwqldcOH-sRR-puy1Yewx_AtnflHC/view?usp=sharing,https://drive.google.com/file/d/19C8fAAhgEX5E_QiUmbMNDzHBMqBOC8i6/view?usp=sharing,,,,Restaurant,DIFC,,,Greek,12:00 - 02:00,All opening hours,1000,"Gaia,Friday",,"Gaia,""Sea Bream Carpaccio | Black Truffle Spaghetti""","Gaia,Yes",6,9,5,10,"Gaia,No","Gaia,Indoor","Gaia,Yes","Gaia,Smart Elegant","Gaia,Yes","Gaia,""Dubai’s iconic Greek dining""","Gaia,Instagram / venue request,High-End Greek Mediterranean,Greek mezze; taramasalata; octopus,Whole grilled fish; lamb chops; seafood pasta,Greek spritz; premium wine,Whole grilled fish,450–700,Seafood; Vegetarian options,High-end iconic Greek",
25,Amazonico,https://maps.app.goo.gl/Z6VWzrvMDdDDphED8,https://drive.google.com/file/d/1xq8I4rF8qwRaAHwO_t94lde9iXHHF3ka/view?usp=sharing,https://drive.google.com/file/d/16AgKl2Qw8xPAWT3SThPM8_slIHj4-ZS6/view?usp=sharing, 045713999,,,Restaurant,DIFC,600-750 pp 5% - 750+ pp -8%,Yes early seating,South American,12:00 - 02:00,All opening hours,500,"Amazonico,Friday",,"Amazonico,""Salmon Tostadas | Arroz Chaufa""","Amazonico,Yes",7,8,8,9,"Amazonico,No","Amazonico,Both","Amazonico,Yes","Amazonico,Smart Elegant","Amazonico,Yes","Amazonico,""Tropical jungle dining""","Amazonico,https://www.amazonico.com/dubai/menus,Latin American Fine Dining,Sushi; ceviche; small plates,Grilled meats; seafood; Amazonian mains,Tropical cocktails; signature mixes,Grilled meats & ceviche,450–750,Seafood; Vegetarian; GF options,Amazonian-inspired fine dining",
26,Amelia,https://maps.app.goo.gl/A6zi1TMGnDLbpejp6,https://drive.google.com/file/d/1wXszil4OPNrd1bl4bZmWcCJ0-9zMaRmd/view?usp=sharing,https://drive.google.com/file/d/19PmiChbpF_yw61kaAa73s4qug5TaHOpg/view?usp=sharing,043282805,,,Restaurant,Downtown,10% above 2K,Yes early seating,Nikkei and Mediterranean,12:00 - 02:00,All opening hours,500,"Amelia,Friday",,"Amelia,""Black Cod with Miso | Crispy Prawns with Passionfruit""","Amelia,Yes",8,6,6,7,"Amelia,No","Amelia,Indoor","Amelia,Yes","Amelia,Smart Elegant","Amelia,Yes","Amelia,""Neo-Japanese Peruvian gastronomy""","Amelia,Instagram / venue request,Japanese-Peruvian Fusion (Nikkei),Ceviche; sushi; sharing starters,Wagyu; seafood; fusion mains,Creative cocktails; sake,Sushi & wagyu,400–650,Seafood; GF options,Nikkei-Mediterranean fusion",
27,Aretha,https://maps.app.goo.gl/RH6N9vmTk49FNo2x9,https://drive.google.com/file/d/11QTbQc6OKVOhZ_Woj49z60VuODVDoWoF/view?usp=sharing,https://drive.google.com/file/d/1ELsEJ9ntuFR7mAzDzkAuzr3uY_Ku1lyW/view?usp=sharing,045400100,,,Restaurant,Palm Jumeirah,10%,No,Continental,12:00 - 02:00,All opening hours,500,"Aretha,Friday",25%,"Aretha,""Wagyu Beef Carpaccio | Grilled King Prawns""","Aretha,Yes",6,5,6,6,"Aretha,Yes","Aretha,Both","Aretha,No","Aretha,Smart Casual","Aretha,Yes","Aretha,""Retro-style dinner party""","Aretha,Instagram / venue request,Retro Dinner Party & Lounge,Comfort starters; sharers,Modern comfort mains; grilled dishes,Classic cocktails; champagne,Sharing mains,300–550,Party focused; Casual,Retro-style dinner lounge",
28,Arrogante,https://maps.app.goo.gl/AVgZpZfdWKqejRV79,https://drive.google.com/file/d/1oI8gcWkKlNAhizOnRefauBTWLMRjR2xI/view?usp=sharing,https://drive.google.com/file/d/1Q4KrmTYIkuyIdz8dQOElENi8eFf544TL/view?usp=sharing,045703653,,,Restaurant,Downtown,10%,Yes,Italian,12:00 - 02:00,All opening hours,500,"Arrogante,Friday",,"Arrogante,""Pistachio Mortadella Pizza | Truffle Carbonara""","Arrogante,Yes",6,5,6,6,"Arrogante,No","Arrogante,Indoor","Arrogante,No","Arrogante,Smart Casual","Arrogante,Yes","Arrogante,""Italian dining with flair""","Arrogante,Instagram / venue request,Italian Dining with Entertainment,Antipasti; burrata; focaccia,Pasta; pizza; Italian mains,Italian spritz; wine,Pasta & pizza,300–500,Vegetarian; Italian classics,Lively Italian with flair",
29,Bar De Pres,https://maps.app.goo.gl/Ryrc2sq5ZLE8urjU9,https://drive.google.com/file/d/1EGiMn6cAszOHmpdKOHg3L1UwuGdMEcvn/view?usp=sharing,https://drive.google.com/file/d/1BBjd61CcXQRl3lXAd7WqSl0vT4dA_um0/view?usp=sharing,044981616,,,Restaurant,DIFC,600-750 pp 5% - 750+ pp -10%,Yes early seating,French Japanese,12:00 - 02:00,All opening hours,500,"Bar De Pres,Friday",25%,"Bar De Pres,""Caviar & Blinis | King Crab Salad""","Bar De Pres,Yes",6,5,8,6,"Bar De Pres,No","Bar De Pres,Indoor","Bar De Pres,Yes","Bar De Pres,Smart Elegant","Bar De Pres,Yes","Bar De Pres,""French-Japanese luxury dining""","Bar De Pres,Instagram / venue request,French-Japanese Fine Dining,Sashimi; foie gras; small plates,Seafood; premium meats; fusion mains,Cocktails; sake; wine,French-Japanese fusion dishes,450–700,Seafood; GF options,Refined French-Japanese",
30,Billionaire,https://maps.app.goo.gl/LeYbegof946S6xa6A,https://drive.google.com/file/d/1DcbHg2IpXi_MK_ExtLTb8mIqgykSb5ap/view?usp=sharing,https://drive.google.com/file/d/1IujIIpBXFrWmS2X3kF3_N91vbi3gUBLb/view?usp=sharing,0543294984,,,Restaurant,Downtown,10%,No,International,12:00 - 02:00,All opening hours,1000,"Billionaire,Friday",,"Billionaire,""Billionaire Roll | Wagyu Tenderloin""","Billionaire,Yes",9,7,10,10,"Billionaire,No","Billionaire,Indoor","Billionaire,No","Billionaire,Club Glam","Billionaire,Yes","Billionaire,""Dinner show entertainment""","Billionaire,Instagram / venue request,Dinner Show & Nightlife,Fine starters; caviar; sharing plates,Premium meats; seafood; pasta,Show cocktails; champagne,Signature dinner show dishes,500–900,Party focused; Luxury,Bespoke dinner show experience",
31,Carnival,https://maps.app.goo.gl/oUUoB4jc28MDHLoK6,https://drive.google.com/file/d/1g9qdoDlSjZ2I0Pz5A4Bjd6VevFp2IBeF/view?usp=sharing,https://drive.google.com/file/d/1C53zJ0reqdAzsMqfHo4Znk7ztvMM0hx5/view?usp=sharing,8001604,,,Restaurant,DIFC,10%,Only on Sundays,Indian,12:00 - 02:00,All opening hours,500,"Carnival,Friday",25%,"Carnival,""Mushroom Chai | Tandoori Chicken Taco""","Carnival,Yes",6,5,6,6,"Carnival,No","Carnival,Indoor","Carnival,No","Carnival,Smart Casual","Carnival,Yes","Carnival,""Progressive Indian culinary theatre""","Carnival,Instagram / venue request,Progressive Indian Fine Dining,Indian small plates; street food bites,Modern Indian mains; grills; curries,Spiced cocktails; wine,Modern Indian mains,300–550,Vegetarian; Halal; Indian,Modern Indian theatre",
32,Ce La Vi,https://maps.app.goo.gl/3shM9EPVryVdH3VZ8,https://drive.google.com/file/d/1LHWAdPTXvpCJ5BwZihQB0F3dsrLYNINe/view?usp=sharing,https://drive.google.com/file/d/1FuK1aRkvjqJAIPkEocWBqzhEMvAbp6lI/view?usp=sharing,045826111,,,Restaurant,Downtown,10% above 5K,Yes early seating,Asian,12:00 - 02:00,All opening hours,500,"Ce La Vi,Friday",,"Ce La Vi,""Lobster & Wagyu Bolognese | Truffle Sushi Rolls""","Ce La Vi,Yes",8,9,10,10,"Ce La Vi,Yes","Ce La Vi,Both","Ce La Vi,Yes","Ce La Vi,Smart Elegant","Ce La Vi,Yes","Ce La Vi,""Rooftop glamour with skyline views""","Ce La Vi,https://www.celavi.com/en/dubai/menus,Asian Fusion Rooftop Dining,Sushi; sashimi; small plates,Black cod; wagyu; seafood mains,Signature skyline cocktails,Black cod & wagyu,400–700,Seafood; Vegetarian; GF options,Asian rooftop glamour",
33,Chic Nonna,https://maps.app.goo.gl/vnyXW46eB7cWkqEq5,https://drive.google.com/file/d/1AXnyj13rzxphENkp0CdqQcqfW52cU26U/view?usp=sharing,https://drive.google.com/file/d/1ML851bZKAbAu8gYvXkC-IlRznIi_yywZ/view?usp=sharing,046052000,,,Restaurant,DIFC,7%,Yes early seating,Italian,12:00 - 02:00,,500,"Chic Nonna,Friday",25%,"Chic Nonna,""Veal Milanese | Truffle Tagliolini""","Chic Nonna,Yes",2,6,5,6,"Chic Nonna,No","Chic Nonna,Indoor","Chic Nonna,Yes","Chic Nonna,Smart Elegant","Chic Nonna,Yes","Chic Nonna,""Italian fine dining""","Chic Nonna,Instagram / venue request,Italian Fine Dining,Antipasti; burrata; carpaccio,Pasta; risotto; Italian mains,Italian wines; spritz,Pasta & risotto,350–600,Vegetarian; Italian classics,Refined Italian fine dining",
34,Cinque,https://maps.app.goo.gl/4eJKJb7dqA3Key576,https://drive.google.com/file/d/1oEcBp3Wbz_coaeKfgq2JITZVnBwf8iMF/view?usp=sharing,https://drive.google.com/file/d/1-9eqN5GCjm4x7SVIY6F-4lBXQq7ntihC/view?usp=sharing,044559989,,,Restaurant,Palm Jumeirah,10% above 3K min net spend,Yes early seating,Italian,12:00 - 02:00,All opening hours,500,"Cinque,Saturday",,"Cinque,""Truffle & Burrata Pizza | Lobster Linguine""","Cinque,Yes",6,6,5,6,"Cinque,Yes","Cinque,Outdoor","Cinque,Yes","Cinque,Smart Elegant","Cinque,Yes","Cinque,""Italian coastal luxury""","Cinque,Instagram / venue request,Italian Coastal Luxury,Seafood starters; burrata,Seafood pasta; grilled fish; premium mains,Italian wines; cocktails,Seafood pasta & fish,400–650,Seafood; Vegetarian options,Coastal Italian elegance",
35,Cou Cou,https://maps.app.goo.gl/WbNcGPTikMLt8XZs7,https://drive.google.com/file/d/1QdarM6ns9BRWhqISUzg01MB0ai90A67d/view?usp=sharing,https://drive.google.com/file/d/1gqqnJTSIyvJq8RA_fJ-Jt-6nVDEECnrV/view?usp=sharing,0524512188,,,Restaurant,Palm Jumeirah,10%,Yes early seating,Mediterranean,12:00 - 02:00,All opening hours,500,"Cou Cou,Friday",,"Cou Cou,""Seafood Tower | Crispy Calamari""","Cou Cou,Yes",9,9,9,10,"Cou Cou,Yes","Cou Cou,Outdoor","Cou Cou,No","Cou Cou,Smart Casual","Cou Cou,Yes","Cou Cou,""Rooftop Mediterranean dining""","Cou Cou,Instagram / venue request,Rooftop Mediterranean Dining,Small plates; salads; mezze,Grilled fish; pasta; mains,Cocktails; champagne,Mediterranean mains,350–600,Vegetarian; Seafood,Sky-high Mediterranean",
36,Coya,https://maps.app.goo.gl/dFvUiH9weHi1UKVp7,https://drive.google.com/file/d/1HBu8KZyajmc5jpXRfanN7-UMH_cq-ML0/view?usp=sharing,https://drive.google.com/file/d/1cvHvb550p47-s16CP1GqOVkYHjkWXKZn/view?usp=sharing,043169600,,,Restaurant,Jumeirah 2,10%,Yes early seating,Peruvian fusion,12:00 - 02:00,All opening hours,500,"Coya,Friday",,"Coya,""Chilean Sea Bass | Yellowtail Tiradito""","Coya,Yes",8,7,9,7,"Coya,Yes","Coya,Both","Coya,Yes","Coya,Smart Elegant","Coya,Yes","Coya,""Vibrant Peruvian fusion""","Coya,https://www.coyarestaurant.com/dubai/menus,Peruvian Fine Dining,Ceviche; tiradito; anticuchos,Grilled meats; seafood; Peruvian classics,Pisco sours; signature cocktails,Ceviche & pisco sour,400–650,Seafood; GF options,Vibrant high-end Peruvian",
37,Dream,https://maps.app.goo.gl/iVYieQb7a59iDFfm9,https://drive.google.com/file/d/1b3VIXqgZlfZkdjUoaPB_V5jJsQQqEraS/view?usp=sharing,https://drive.google.com/file/d/1S_IePnosIctEStW8V1e8vzLk2TCTtJzY/view?usp=sharing,042200224,,,Restaurant,JBR,10% (1000pp min),No,Mediterranean,12:00 - 02:00,All opening hours,500,"Dream,Friday",,"Dream,""Wagyu Striploin | Crispy Prawns""","Dream,Yes",8,8,9,7,"Dream,No","Dream,Indoor","Dream,No","Dream,Club Glam","Dream,Yes","Dream,""Dinner show nightlife fusion""","Dream,Instagram / venue request,Dinner Show & Nightlife Fusion,Sharing starters; sushi; ceviche,Grilled meats; seafood; fusion mains,Show cocktails; champagne,Dinner show signature dishes,500–900,Party focused; Luxury,Immersive dinner show",
38,GAL,https://maps.app.goo.gl/1bu2eHro4G8ZvPKB7,https://drive.google.com/file/d/14uZf2diHrNGVw8S-NXobAT3doAT_KY04/view?usp=sharing,https://drive.google.com/file/d/1aV2VDJonOAcACrdD-Jc9bUmT4zIlZfjw/view?usp=sharing,045897883,,,Restaurant,Downtown,7% (only if monthly combined total booking target reaches 30k),Yes early seating,Turkish,12:00 - 02:00,All opening hours,500,"GAL,Friday",,"GAL,""GAL Sushi Platter | Grilled Tiger Prawns""","GAL,Yes",6,7,7,7,"GAL,No","GAL,Indoor","GAL,No","GAL,Smart Elegant","GAL,Yes","GAL,""Mediterranean nightlife restaurant""","GAL,Instagram / venue request,Mediterranean Nightlife Dining,Small plates; mezze; salads,Grilled fish; premium meats; pasta,Crafted cocktails; wine,Sharing mains,350–600,Vegetarian; Seafood,Lively Turkish Mediterranean",
39,Gatsby,https://maps.app.goo.gl/ibAEJiQ1weThq79c7,https://drive.google.com/file/d/11i8CykgUWYNZg4vITEudiG98yulxBieN/view?usp=sharing,https://drive.google.com/file/d/1vjjYkKTALSr3fZblCeShRIxaUVXMiyK0/view?usp=sharing,045549418,,,Restaurant,Palm Jumeirah,10%,Yes early seating (14+),Spanish,12:00 - 02:00,All opening hours,500,"Gatsby,Friday",25%,"Gatsby,""Beef Fillet Skewers | Smoked Salmon Tartare""","Gatsby,Yes",6,7,6,7,"Gatsby,No","Gatsby,Indoor","Gatsby,No","Gatsby,Club Glam","Gatsby,Yes","Gatsby,""Roaring 1920s dinner club""","Gatsby,Instagram / venue request,1920s Dinner Club & Lounge,Classic starters; sharers,Steaks; seafood; comfort mains,Classic cocktails; champagne,Steak & show dishes,400–700,Party focused; Classic,1920s themed dinner club",
40,Hanu,https://maps.app.goo.gl/6TPxQMd141oGJWfk7,https://drive.google.com/file/d/11YjljeJE52A3jzFZRIOCv39_xB5I-r_F/view?usp=sharing,https://drive.google.com/file/d/1wgHHDSvxjapLnXkFxKkj-2-Bz5BVPEwV/view?usp=sharing,042784844,,,Restaurant,Palm Jumeirah,10%,No,Korean,12:00 - 02:00,All opening hours,500,"Hanu,Friday",,"Hanu,""Korean Wagyu BBQ | Kimchi Fried Rice""","Hanu,No",6,5,5,7,"Hanu,No","Hanu,Indoor","Hanu,No","Hanu,Smart Casual","Hanu,Yes","Hanu,""Korean BBQ experience""","Hanu,Instagram / venue request,Korean BBQ & Grill,Kimchi; banchan; starters,Premium Korean BBQ meats; grills,Soju; Korean cocktails,Korean BBQ meats,350–600,Halal; Meat focused,Modern Korean BBQ",
41,Iliana,https://maps.app.goo.gl/aRuv7KWmpzU4k1nA6,https://drive.google.com/file/d/16tYEBv83OBjESyoSo_R2d1lsYmgqkssy/view?usp=sharing,https://drive.google.com/file/d/1r-Rc6fvN6orWOpPYZb80rO9bXvmltHw9/view?usp=sharing,800323232,,,Restaurant,Marsa Al Arab,5%,Yes early seating,Greek,12:00 - 02:00,All opening hours,500,"Iliana,Friday",,"Iliana,""Greek Sea Bass | Slow-Cooked Lamb Shoulder""","Iliana,No",6,6,5,6,"Iliana,Yes","Iliana,Both","Iliana,Yes","Iliana,Smart Elegant","Iliana,Yes","Iliana,""Modern Greek elegance""","Iliana,Instagram / venue request,Modern Greek Mediterranean,Greek mezze; salads; octopus,Grilled fish; lamb chops; seafood pasta,Greek wines; spritz,Grilled fish & lamb,400–650,Seafood; Vegetarian,Refined Greek elegance",
42,Kaspia,https://maps.app.goo.gl/eGA7WgbirFrZmXDY7,https://drive.google.com/file/d/1996Jj9jvZbTIU-kXoDknQd0khgw_Dn2p/view?usp=sharing,https://drive.google.com/file/d/1_qdKU8sMtRzK2QblscqPxu6TmTCTZl6k/view?usp=share_link,042435633,,,Restaurant,Palm Jumeirah,10%,No,Russian,12:00 - 02:00,All opening hours,500,"Kaspia,Saturday",,"Kaspia,""Kaspia Baked Potato with Caviar | Salmon Coulibiac""","Kaspia,Yes",6,8,5,6,"Kaspia,Yes","Kaspia,Outdoor","Kaspia,Yes","Kaspia,Smart Elegant","Kaspia,Yes","Kaspia,""Luxury caviar dining""","Kaspia,Instagram / venue request,Parisian Luxury & Caviar Dining,Service à la Russe; blinis; starters,Seafood; premium meats; classics,Champagne; vodka,Caviar service,700–1200,Seafood; Luxury,Luxury caviar dining",
43,Kinugawa,https://maps.app.goo.gl/L7Ke583YurHDtGKW6,https://drive.google.com/file/d/1cmoXkoyuuHCsSFnPxvkH33Ei8qmEiXSj/view?usp=sharing,https://drive.google.com/file/d/1NpCJblSNdaD_ff4eJWKROKT6eWLH5TfC/view?usp=sharing,800323232,,,Restaurant,Marsa Al Arab,5%,Yes early seating 7+,Japanese and French,12:00 - 02:00,All opening hours,500,"Kinugawa,Friday",,"Kinugawa,""Crispy Rice Tuna | Black Cod Yuzu Miso""","Kinugawa,Yes",6,8,5,7,"Kinugawa,No","Kinugawa,Indoor","Kinugawa,Yes","Kinugawa,Smart Elegant","Kinugawa,No","Kinugawa,""Contemporary Japanese gastronomy""","Kinugawa,Instagram / venue request,Contemporary Japanese Dining,Sashimi; sushi; gyoza,Black cod; wagyu; seafood grills,Sake; Japanese cocktails,Black cod & sushi,450–700,Seafood; GF options,Japanese French gastronomy",
44,L'amo Bistro,https://maps.app.goo.gl/coQEBg3FLj3ezmxb7,https://drive.google.com/file/d/1-_3BAp9AzpeX7OKnjKbrtMmX_F227k-T/view?usp=sharing,https://drive.google.com/file/d/1NAYs9vQtUvCHTjxaH8ix-mqb9FmqLa-M/view?usp=share_link,042784800,,,Restaurant,Dubai Harbor,10%,Yes,Italian,12:00 - 02:00,All opening hours,500,"L'amo Bistro,Friday",,"L'amo Bistro,""Linguine alle Vongole | Amalfi Lemon Sea Bass""","L'amo Bistro,No",6,6,5,6,"L'amo Bistro,Yes","L'amo Bistro,Outdoor","L'amo Bistro,Yes","L'amo Bistro,Smart Elegant","L'amo Bistro,No","L'amo Bistro,""Italian seafood excellence""","L'amo Bistro,Instagram / venue request,Italian Seafood Bistro,Seafood antipasti; crudo,Seafood pasta; grilled fish; risotto,Italian wines; spritz,Seafood pasta,350–600,Seafood; Italian classics,Premier Italian seafood",
45,La Nina,https://maps.app.goo.gl/mbDGgV3SYS7z7Qxg8,https://drive.google.com/file/d/1DlXhAXutYX8z3e1sjZ-6J3FpPpPzpvs6/view?usp=sharing,https://drive.google.com/file/d/1O7GpKaCmx8G5Ed-oNLnK7g0ReBDUFPls/view?usp=sharing,043351300,,,Restaurant,DIFC,5%,Yes early seating,Latino Iberian,12:00 - 02:00,All opening hours,500,"La Nina,Friday",25%,"La Nina,""Portuguese Piri Piri Chicken | Grilled Octopus""","La Nina,Yes",6,5,5,6,"La Nina,No","La Nina,Indoor","La Nina,Yes","La Nina,Smart Elegant","La Nina,No","La Nina,""Latin Mediterranean flavours""","La Nina,Instagram / venue request,Latin Mediterranean Dining,Tapas; ceviche; sharing plates,Grilled meats; seafood; fusion mains,Latin cocktails; wine,Sharing mains,350–600,Seafood; Vegetarian options,Lively Latin Iberian",
46,Ly-La,https://maps.app.goo.gl/6uVioJ6SuRNxLqB47,https://drive.google.com/file/d/1GG34KvB4SSGHqpQ_EhyvF4DG8vG2dOff/view?usp=sharing,XXX,0566800430,,,Restaurant,DIFC,10%,No,Middle Eastern,12:00 - 02:00,All opening hours,500,"Ly-La,Friday",,"Ly-La,""Wagyu Lamb Kofta | Charcoal Grilled Prawns""","Ly-La,Yes",6,5,5,6,"Ly-La,No","Ly-La,Indoor","Ly-La,No","Ly-La,Smart Casual","Ly-La,Yes","Ly-La,""Middle Eastern coastal dining""","Ly-La,Instagram / venue request,Middle Eastern Coastal Dining,Hot & cold mezze; salads,Grilled seafood; Middle Eastern mains,Middle Eastern cocktails,Grilled seafood & mezze,300–500,Halal; Vegetarian; Seafood,Coastal Middle Eastern",
47,Maiden Shanghai,https://maps.app.goo.gl/UBwMXTjygZXnioX18,https://drive.google.com/file/d/1K_xS1Zj5NM_QKidQy8_PsuY8xg0C2y-_/view?usp=sharing,https://drive.google.com/file/d/1H6tHP0f8EcQsY0EznQWlf5BnoruGK1Cw/view?usp=sharing,044559989,,,Restaurant,Palm Jumeirah,10% above 3K min net spend,Yes early,Chinese,12:00 - 02:00,All opening hours,500,"Maiden Shanghai,Friday",,"Maiden Shanghai,""Kung Pao Chicken | Peking Duck""","Maiden Shanghai,Yes",6,5,5,6,"Maiden Shanghai,Yes","Maiden Shanghai,Both","Maiden Shanghai,No","Maiden Shanghai,Smart Elegant","Maiden Shanghai,Yes","Maiden Shanghai,""Chinese gourmet dining""","Maiden Shanghai,Instagram / venue request,Contemporary Chinese Fine Dining,Dim sum; starters,Peking duck; seafood mains; Chinese classics,Tea cocktails; wine,Peking duck,400–700,Seafood; Chinese classics,Gourmet Chinese dining",
48,Maison De Curry,https://maps.app.goo.gl/os4wgidNpJPttsRL9,https://drive.google.com/file/d/1pVgvizI7W3_31XCJbbSTB1FBer2J0Vp-/view?usp=sharing,https://drive.google.com/file/d/1-0c25SXnjUgkS75AxMNMDlaTUh_O7jNa/view?usp=sharing,0524066183,,,Restaurant,Downtown,10%,No,Indian,12:00 - 02:00,All opening hours,500,"Maison De Curry,Saturday",,"Maison De Curry,""Red Lobster Curry | Chicken Katsu Curry""","Maison De Curry,Yes",6,5,5,6,"Maison De Curry,Yes","Maison De Curry,Indoor","Maison De Curry,No","Maison De Curry,Smart Casual","Maison De Curry,No","Maison De Curry,""Waterfront Asian comfort food""","Maison De Curry,Instagram / venue request,Modern Indian Dining,Indian starters; street bites,Contemporary curries; grills; mains,Spiced cocktails; lassi,Signature curries,250–450,Vegetarian; Halal; Indian,Modern Indian waterfront",
49,Maison Revka,https://maps.app.goo.gl/qbpEfceTFesd1qup9,https://drive.google.com/file/d/1OwKsz3jjnC8g3bQsDykwawP_AtTCiB1a/view?usp=sharing,https://drive.google.com/file/d/1jxUj8NEcaTGJBcZiukkp9jBGatMd7GUg/view?usp=sharing,045432900,,,Restaurant,Blue Waters,10% (1000 aed min pp),Yes day time for lunch,Slavic,12:00 - 02:00,All opening hours,500,"Maison Revka,Friday",,"Maison Revka,""Revka King Crab Pasta | Wagyu Stroganoff""","Maison Revka,Yes",6,5,5,6,"Maison Revka,Yes","Maison Revka,Indoor","Maison Revka,Yes","Maison Revka,Smart Elegant","Maison Revka,Yes","Maison Revka,""Parisian luxury dining""","Maison Revka,Instagram / venue request,Parisian Luxury Dining,Slavic & French starters,Seafood; premium meats; classics,Champagne; classic cocktails,Signature French dishes,450–750,Seafood; Luxury,Parisian Slavic elegance",
50,Mamabella,https://maps.app.goo.gl/oabRPMZFDK1Yerb16,https://drive.google.com/file/d/1I_hjQBgVd97wi7P_axgdumeJ6Ud5iluB/view?usp=sharing,https://drive.google.com/file/d/1p1Dhcxfx0bq1e86jeWpFPnrslOZzN6TH/view?usp=sharing,044308999,,,Restaurant,Downtown,10%,Yes early seating,Italian,12:00 - 02:00,All opening hours,500,"Mamabella,Friday",,"Mamabella,""Signature Mezze Platter | Lamb Chops""","Mamabella,No",6,5,5,6,"Mamabella,No","Mamabella,Indoor","Mamabella,No","Mamabella,Smart Casual","Mamabella,Yes","Mamabella,""Italian comfort dining""","Mamabella,Instagram / venue request,Italian Mediterranean Dining,Antipasti; pasta; pizza,Grilled meats; seafood,Italian wines; spritz,Classic Italian comfort,300–500,Vegetarian; Italian,Homestyle Italian",
51,Mimi Kakushi,https://maps.app.goo.gl/PTegLQ7mHRhwKhBS8,https://drive.google.com/file/d/1NqM3pro4DAECAY0bjMi3tXGhZ3MPdwPM/view?usp=sharing,https://drive.google.com/file/d/1ydndomL5c4idnowCI_m9nk0gsDZE4-to/view?usp=sharing,043794811,,,Restaurant,Four Seasons,10%,Yes,Japanese,12:00 - 02:00,All opening hours,500,"Mimi Kakushi,Friday",,"Mimi Kakushi,""Black Cod with Yuzu Miso | Wagyu Gyoza""","Mimi Kakushi,Yes",6,5,5,6,"Mimi Kakushi,Yes","Mimi Kakushi,Indoor","Mimi Kakushi,Yes","Mimi Kakushi,Smart Elegant","Mimi Kakushi,Yes","Mimi Kakushi,""1920s Osaka-inspired dining""","Mimi Kakushi,Instagram / venue request,1920s Osaka Japanese Dining,Sushi; small plates; starters,Robata grills; wagyu; seafood,Sake cocktails; Japanese mixes,Robata grills & sushi,400–650,Seafood; GF options,Osaka-inspired dining",
52,Mott 32,https://maps.app.goo.gl/LNibScnh33ntWxCQA,https://drive.google.com/file/d/1OVgjmYOTpexXhs-hiyqZdp6omc-Nuv6z/view?usp=sharing,https://drive.google.com/file/d/1b8OppTUzSzR-lNuz9u2daqZP_UtqeUgE/view?usp=sharing,042784832,,,Restaurant,JBR,10%,Yes early seating,Chinese,12:00 - 02:00,All opening hours,500,"Mott 32,Friday",,"Mott 32,""Peking Duck | Char Siu Iberico Pork""","Mott 32,Yes",6,5,5,6,"Mott 32,No","Mott 32,Indoor","Mott 32,Yes","Mott 32,Smart Elegant","Mott 32,No","Mott 32,""World-class Chinese fine dining""","Mott 32,https://mott32.com/dubai/menus,Chinese Fine Dining,Dim sum; starters,Applewood Peking duck; seafood mains,Tea cocktails; wine,Peking duck,500–900,Seafood; Chinese classics,Elite Chinese fine dining",
53,Nahate,https://maps.app.goo.gl/Si3RJvdv6yWw4Wjs6,https://drive.google.com/file/d/1iGq6E-Hxb_gJibJoMAT0L8jtmsqBsTTA/view?usp=sharing,https://drive.google.com/file/d/1JqNXxUlbG2So5boLbN-R8tAwxOdJmgZU/view?usp=sharing,0522080007,,,Restaurant,DIFC,10%,No,Middle Eastern,12:00 - 02:00,All opening hours,1000,"Nahate,Friday",,"Nahate,""Lebanese Mixed Grill | Spiced Lamb Kibbeh""","Nahate,No",8,6,9,7,"Nahate,No","Nahate,Indoor","Nahate,No","Nahate,Smart Casual","Nahate,No","Nahate,""Traditional Levantine dining""","Nahate,Instagram / venue request,Traditional Levantine Dining,Cold & hot mezze,Grilled meats; Levantine mains,Arabic drinks; wine,Grills & mezze,250–450,Halal; Vegetarian,Authentic Levantine",
54,Nazcaa,https://maps.app.goo.gl/SvJh2n4ZHqguH4LC7,https://drive.google.com/file/d/1sRoA6dPET7u1mNlH7HSpwk9_CyWLFLSN/view?usp=sharing,https://drive.google.com/file/d/1CBCphaGjAQ1Bx7ulyuG_x5WRrUzbfRAK/view?usp=sharing,045424200,,,Restaurant,Downtown,10%,Yes early seating,Nikkei,12:00 - 02:00,All opening hours,500,"Nazcaa,Friday",,"Nazcaa,""Nikkei Ceviche | Anticucho Skewers""","Nazcaa,Yes",7,6,5,6,"Nazcaa,Yes","Nazcaa,Both","Nazcaa,No","Nazcaa,Smart Casual","Nazcaa,Yes","Nazcaa,""Japanese-Peruvian fusion""","Nazcaa,Instagram / venue request,Japanese-Peruvian Fusion (Nikkei),Ceviche; sushi; starters,Grilled meats; seafood; fusion mains,Pisco & sake cocktails,Ceviche & sushi,350–600,Seafood; GF options,Japanese-Peruvian fusion",
55,Opa,https://maps.app.goo.gl/6GaW4df1iHCG4QJP6,https://drive.google.com/file/d/1IV_S_CTpuT8s0hBPEGBo4bDgqyFaQjAE/view?usp=sharing,https://drive.google.com/file/d/1P1HKLul_CZh-e38nw1SY_1VTSso-6a2T/view?usp=sharing,043570557,,,Restaurant,Fairmont,5%,Yes early seating,Greek,12:00 - 02:00,All opening hours,500,"Opa,Friday",,"Opa,""OPA Hummus | Lamb Kleftiko""","Opa,Yes",8,6,8,7,"Opa,No","Opa,Indoor","Opa,No","Opa,Smart Casual","Opa,Yes","Opa,""Interactive Greek nightlife dining""","Opa,Instagram / venue request,Interactive Greek Dining,Greek mezze; saganaki,Grilled meats; Greek classics,Greek cocktails; wine,Saganaki & Greek classics,300–550,Vegetarian; Seafood,Plate-smashing Greek party",
56,Ram & Roll,https://maps.app.goo.gl/3oHYjRqqRi6a6Bou5,https://drive.google.com/file/d/1D_lmZyLnlMkPeZrGlb9Qw-BHl7Szog3A/view?usp=sharing,https://drive.google.com/file/d/18Xtk91RG6taFxB4C6ophJ6JZbd3-QNF0/view?usp=sharing,044308222,,,Restaurant,Downtown,10%,Yes,Comfort Dining,12:00 - 02:00,All opening hours,500,"Ram & Roll,Saturday",,"Ram & Roll,""Slow-Smoked Brisket Roll | Truffle Fries""","Ram & Roll,No",7,5,6,6,"Ram & Roll,No","Ram & Roll,Indoor","Ram & Roll,No","Ram & Roll,Casual","Ram & Roll,No","Ram & Roll,""Comfort food street concept""","Ram & Roll,Instagram / venue request,Casual Comfort Food,Dips; sharers,Wraps; comfort mains; casual bites,Soft drinks; casual cocktails,Comfort wraps,150–300,Casual; Vegetarian,Casual comfort street food",
57,Rialto,https://maps.app.goo.gl/aauBjkFphg7eJbYv8,https://drive.google.com/file/d/1bWgY5zJfK1ZwMWRnuwtmNp81kv29sdcT/view?usp=sharing,https://drive.google.com/file/d/1XvUBiogIMbMpSaFS6D8VS7isEJh2mojd/view?usp=sharing,800323232,,,Restaurant,Marsa Al Arab,5%,Yes early seating,Italian,12:00 - 02:00,All opening hours,500,"Rialto,Friday",,"Rialto,""Truffle Mushroom Risotto | Veal Ossobuco""","Rialto,Yes",6,5,5,6,"Rialto,No","Rialto,Indoor","Rialto,Yes","Rialto,Smart Elegant","Rialto,No","Rialto,""Modern Italian dining""","Rialto,Instagram / venue request,Modern Italian Dining,Antipasti; burrata,Pasta; risotto; Italian mains,Italian wines; spritz,Pasta & risotto,300–550,Vegetarian; Italian classics,Sophisticated modern Italian",
58,Salvaje,https://maps.app.goo.gl/HCgJ747EEqqWMPL77,https://drive.google.com/file/d/14lST8_dLG6BlvNk3GLe_PaLCebErv-s8/view?usp=sharing,https://drive.google.com/file/d/1sLV_qiaX9fhZadbl1yxU8xHHZD0espsR/view?usp=sharing,045703653,,,Restaurant,Downtown,10%,Yes early seating,Japanese fusion,12:00 - 02:00,All opening hours,500,"Salvaje,Friday",,"Salvaje,""Salvaje Sushi Roll | Crispy Rice with Spicy Tuna""","Salvaje,Yes",8,6,8,7,"Salvaje,Yes","Salvaje,Indoor","Salvaje,No","Salvaje,Smart Elegant","Salvaje,Yes","Salvaje,""Wild Japanese-Latin experience""","Salvaje,Instagram / venue request,Wild Japanese-Latin Dining,Sushi; ceviche; starters,Grilled meats; seafood; fusion mains,Show cocktails; champagne,Sushi & fusion grills,450–750,Seafood; Party focused,Wild Japanese-Latin party",
59,Sexy Fish,https://maps.app.goo.gl/t34CDq9D125VBDCJ6,https://drive.google.com/file/d/1DJNbY3ifa6cROAOhiKE_evnSSpylPJmQ/view?usp=sharing,https://drive.google.com/file/d/18UFU0i2PkTLewCQId_376VXdbolqUyvq/view?usp=sharing,043819000,,,Restaurant,DIFC,10% over 2k,Yes early seating,Asian fusion,12:00 - 02:00,All opening hours,500,"Sexy Fish,Friday",,"Sexy Fish,""Black Cod with Yuzu | Crispy Duck Salad""","Sexy Fish,Yes",7,7,8,7,"Sexy Fish,No","Sexy Fish,Indoor","Sexy Fish,Yes","Sexy Fish,Smart Elegant","Sexy Fish,Yes","Sexy Fish,""Ultra-glam Asian seafood""","Sexy Fish,Instagram / venue request,Ultra-Glam Asian Seafood,Seafood starters; sashimi,Seafood mains; premium fish; wagyu,Creative cocktails; champagne,Seafood & fish mains,500–900,Seafood; GF options,Ultra-glam Asian seafood",
60,Signor Sassi,https://maps.app.goo.gl/1N1aQ8C9KXNA6LVD6,https://drive.google.com/file/d/1nrKIgBNQfwm7CEeAKRTd4RLEzaeD-GNw/view?usp=sharing,https://drive.google.com/file/d/11LeG0yBn0-OlnqBlen2qBeGhY4gZWzlH/view?usp=sharing,042784848,,,Restaurant,Palm Jumeirah,10%,Yes early seating,Italian,12:00 - 02:00,All opening hours,500,"Signor Sassi,Friday",,"Signor Sassi,""Spaghetti al Limone | Vitello Tonnato""","Signor Sassi,Yes",6,6,5,6,"Signor Sassi,Yes","Signor Sassi,Both","Signor Sassi,Yes","Signor Sassi,Smart Elegant","Signor Sassi,Yes","Signor Sassi,""Old-school Italian luxury""","Signor Sassi,Instagram / venue request,Classic Italian Luxury,Antipasti; burrata; carpaccio,Pasta; veal; Italian classics,Italian wines; spritz,Classic pasta dishes,400–650,Vegetarian; Italian classics,Old-school Italian luxury",
61,Sushi Samba,https://maps.app.goo.gl/zzaS5MRHgX8fnUmi9,https://drive.google.com/file/d/1FPTJQKmT13sD-LEIRnNpmGV7dKY_LSPd/view?usp=sharing,https://drive.google.com/file/d/19VdO-2bTwm8eTUN4pKXusok3UK7JCGPr/view?usp=sharing,042784888,,,Restaurant,Palm Jumeirah,Lunch 5% over 1400 / Dinner 5% over 2000 / Min net Spend 500 pp,Yes early seating,Asain fusion,12:00 - 02:00,All opening hours,500,"Sushi Samba,Friday",,"Sushi Samba,""Wagyu Gyoza | Samba Roll""","Sushi Samba,Yes",7,9,9,10,"Sushi Samba,Yes","Sushi Samba,Outdoor","Sushi Samba,No","Sushi Samba,Smart Elegant","Sushi Samba,Yes","Sushi Samba,""Nikkei fusion with skyline views""","Sushi Samba,https://sushisamba.com/location/dubai/menus,Japanese-Brazilian Fusion,Sushi; ceviche; small plates,Grilled meats; seafood; fusion mains,Signature cocktails,Sushi & ceviche,400–700,Seafood; GF options,Japanese Brazilian fusion",
62,China Tang,https://maps.app.goo.gl/EP9nEmR8reXdowX1A,https://drive.google.com/file/d/1jHxY69lmdxhloLyceqIK7NbjaUyUsbrr/view?usp=sharing,https://drive.google.com/file/d/1vBtRTRqWek9JjWhqffP5MOIk6K-nfVyH/view?usp=sharing,042957464,,,Restaurant,Downtown,10%,Yes early seating,Cantonese,12:00 - 02:00,All opening hours,500,"China Tang,Friday",,"China Tang,""Crispy Duck | Prawn Dumplings""","China Tang,Yes",6,7,6,6,"China Tang,No","China Tang,Indoor","China Tang,Yes","China Tang,Smart Elegant","China Tang,No","China Tang,""Classic Cantonese luxury""","China Tang,Instagram / venue request,Classic Cantonese Fine Dining,Dim sum; starters,Cantonese classics; seafood,Chinese teas; wine,Dim sum & mains,400–700,Seafood; Chinese classics,Classic Cantonese luxury",
63,Tattu,https://maps.app.goo.gl/BwAciwdnJmVkuS379,https://drive.google.com/file/d/1KGcEh14JJT65_DaZ8yj7l_16jsqy8oIK/view?usp=sharing,https://drive.google.com/file/d/1xw9NPmoAKWDRryL7YzxIySwOXO1_sIMd/view?usp=sharing,044985400,,,Restaurant,Dubai Marina,5-10%,Yes early seating,Asian fusion,12:00 - 02:00,All opening hours,500,"Tattu,Friday",,"Tattu,""Black Pepper Beef | Crispy Duck Pancakes""","Tattu,Yes",7,8,8,7,"Tattu,No","Tattu,Indoor","Tattu,Yes","Tattu,Smart Elegant","Tattu,Yes","Tattu,""Contemporary Asian artistry""","Tattu,https://tattu.co.uk/location/dubai/menus,Modern Chinese Fine Dining,Dim sum; starters,Peking duck; premium mains,Signature cocktails,Peking duck,450–750,Seafood; Chinese classics,Contemporary Asian art",
64,Theater,https://maps.app.goo.gl/7mxUhdXFjcqUnCRb8,https://drive.google.com/file/d/1xsdB3821SDXEirlvGqjcrWwSBTu6wJ5J/view?usp=sharing,https://drive.google.com/file/d/1czjvsVGWJqtcEbBHKNx0f9oiOrQ_WSOd/view?usp=sharing,042222268,,,Restaurant,Fairmont,10%,No,Show Dining,12:00 - 02:00,All opening hours,500,"Theater,Friday",,"Theater,""Wagyu Striploin | Lobster Linguine""","Theater,Yes",8,8,8,7,"Theater,No","Theater,Indoor","Theater,No","Theater,Club Glam","Theater,Yes","Theater,""Immersive dinner show""","Theater,Instagram / venue request,Immersive Dinner Show Dining,Sharing starters,Show-focused mains; fusion dishes,Show cocktails; champagne,Dinner show dishes,500–900,Party focused,Immersive performance dinner",
65,Trésind,https://maps.app.goo.gl/37n5HamUQyRkQwTD9,https://drive.google.com/file/d/1IE0NbObRJwONBaVcIiaoiL8tCOUHHnVH/view?usp=sharing,https://drive.google.com/file/d/1vTo7gbU8M9kGqOZ2C12Zfk-cdoHRJnvZ/view?usp=sharing,8001604,,,Restaurant,Dubai Marina,10%,Sundays,Indian,12:00 - 02:00,All opening hours,500,"Trésind,Friday",,"Trésind,""Avocado Delice | Lamb Raan""","Trésind,Yes",5,6,5,6,"Trésind,No","Trésind,Indoor","Trésind,Yes","Trésind,Smart Elegant","Trésind,No","Trésind,""Progressive Indian fine dining""","Trésind,Instagram / venue request,Progressive Indian Fine Dining,Indian tasting starters,Modern Indian tasting menus,Paired wines; cocktails,Tasting menu,450–800,Vegetarian; Indian; Halal options,Michelin Indian concept",
66,Urla,https://maps.app.goo.gl/k9fsbefdjBSABFRw6,https://drive.google.com/file/d/1PspTE3JdFxqMP0RcPRuM2KIzfI-zFvIL/view?usp=sharing,https://drive.google.com/file/d/1Ofuw6oSXI6cmk799WN_YFrIR39JWIWjS/view?usp=sharing,0525545997,,,Restaurant,Downtown,7% (only if monthly combined total booking target reaches 30k),Yes early seating,Aegean,12:00 - 02:00,All opening hours,500,"Urla,Friday",,"Urla,""Turkish Seabass | Wagyu Tenderloin Skewers""","Urla,Yes",5,6,5,6,"Urla,Yes","Urla,Outdoor","Urla,Yes","Urla,Smart Elegant","Urla,Yes","Urla,""Aegean coastal dining""","Urla,Instagram / venue request,Aegean Coastal Fine Dining,Meze; seafood starters,Grilled fish; Aegean mains,Turkish wines; cocktails,Grilled fish & meze,350–600,Seafood; Vegetarian,Aegean coastal vibes",
67,Verde Restaurant,https://maps.app.goo.gl/oSUrvSEFJ1EBG3wG7,https://drive.google.com/file/d/1d3b8_jqBFzwnwRWLTjj1Mcu0tGLuCOZQ/view?usp=sharing,https://drive.google.com/file/d/1qzP9R3Ic72I4I2f0L0n_M4-Y_vM_V/view?usp=sharing,043338025,,,Restaurant,Four Seasons,10%,Yes early seating,French,12:00 - 02:00,All opening hours,1000,"Verde Restaurant,Friday",,"Verde Restaurant,""Truffle Artichoke Pasta | Seabass Ceviche""","Verde Restaurant,Yes",9,7,9,9,"Verde Restaurant,Yes","Verde Restaurant,Indoor","Verde Restaurant,No","Verde Restaurant,Smart Elegant","Verde Restaurant,Yes","Verde Restaurant,""Parisian dining party""","Verde Restaurant,Instagram / venue request,Parisian Dining & Lounge,French starters; salads,Classic French mains; grills,Classic cocktails; wine,French classics,350–600,Vegetarian; Seafood,French dining party",
68,Woohoo,https://maps.app.goo.gl/hcugBHxMyHiAqpuZ7,https://drive.google.com/file/d/1iSsG-uRIAMW58PrrBjaCpNVQsHMtNnlm/view?usp=sharing,https://drive.google.com/file/d/1gq_A0DVihDgY5suB-n1M4U9_i19g0Kn2/view?usp=sharing,044308111,,,Restaurant,Downtown,10%,No,Comfort Cafe,12:00 - 02:00,All opening hours,500,"Woohoo,Saturday",,"Woohoo,""Korean Fried Chicken | Bulgogi Beef Bowl""","Woohoo,No",6,5,6,6,"Woohoo,No","Woohoo,Indoor","Woohoo,No","Woohoo,Casual","Woohoo,No","Woohoo,""Casual comfort cafe""","Woohoo,Instagram / venue request,Casual Cafe & Dining,Light bites; snacks,Comfort mains; cafe classics,Coffee; casual drinks,Casual mains,150–300,Casual; Vegetarian,Relaxed comfort cafe",
69,Milos,https://maps.app.goo.gl/KiVjrPMRwbHaW8uD6,https://drive.google.com/file/d/1T77aaYtNSYkXhIe6BMX8hZ668lpnhFp3/view?usp=sharing,https://drive.google.com/file/d/1FStBmxJ3JzWEWDt1kTXPPeCXbjF80eFJ/view?usp=sharing,044262555,,,Restaurant,Palm Jumeirah,10%,Yes,Greek,12:00 - 02:00,All opening hours,1000,"Milos,Friday",,"Milos,""Grilled Octopus | Zucchini & Eggplant Tower""","Milos,Yes",5,9,5,9,"Milos,Yes","Milos,Both","Milos,Yes","Milos,Smart Elegant","Milos,No","Milos,""World-famous Greek seafood""","Milos,https://www.estiatoriomilos.com/location/dubai/menus,Greek Seafood Fine Dining,Raw seafood; mezze,Whole grilled fish; seafood platters,Greek wines; ouzo,Fresh whole fish,500–900,Seafood; GF options,Famous Greek seafood",
70,Nobu by Beach,https://maps.app.goo.gl/wZbLEAk3HetHwu5Q8,https://drive.google.com/file/d/1VAtxJzqGl9KjFcFmONSRKWJOrT8LP3mF/view?usp=sharing,https://drive.google.com/file/d/1mbHc3dGr0gBB_jFLf5fu25szdcBCPpxG/view?usp=sharing,044261600,,,Restaurant,Palm Jumeirah,10%,Yes,Japanese fusion,12:00 - 02:00,All opening hours,1000,"Nobu by Beach,Saturday",,"Nobu by Beach,""Black Cod Miso | Yellowtail Jalapeño""","Nobu by Beach,Yes",7,9,8,9,"Nobu by Beach,Yes","Nobu by Beach,Outdoor","Nobu by Beach,Yes","Nobu by Beach,Resort Chic","Nobu by Beach,Yes","Nobu by Beach,""Luxury beachfront Japanese""","Nobu by Beach,Instagram / venue request,Japanese-Peruvian Beach Dining,Sushi; ceviche; small plates,Black cod miso; seafood mains,Signature Nobu cocktails,Black cod miso,450–800,Seafood; GF options,Luxury beachfront Japanese",
71,Carbone,https://maps.app.goo.gl/K3vnZwgdF43ZRsBJA,https://drive.google.com/file/d/1cc84GBqA59J2Z2cgi48jcKkS1Ru-lvKN/view?usp=sharing,https://drive.google.com/file/d/17SO7jFTHOcSzYPdGXke_qWqx9jm2Kdy9/view?usp=sharing,044260500,,,Restaurant,Palm Jumeirah,10%,No,Italian American,12:00 - 02:00,All opening hours,1000,"Carbone,Friday",,"venue,signature_dish","Carbone,Yes",6,9,7,10,"Carbone,No","Carbone,Indoor","Carbone,Yes","Carbone,Smart Elegant","Carbone,Yes","Carbone,""New York Italian glamour""","Carbone,Instagram / venue request,New York Italian Glamour,Antipasti; Caesar salad,Spicy rigatoni; veal parmesan; classics,Classic cocktails; martinis,Spicy rigatoni vodka,450–750,Vegetarian; Italian classics,NYC Italian glamour",
91,zuma,https://maps.app.goo.gl/PcjR5TEoSyduSD3r7,https://drive.google.com/file/d/1nZoNOAtNf1r7-8wpTRz4dohBRER4nHlz/view?usp=share_link,XXX,,,,Restaurant,DIFC,10%,Yes,Japanese Contemporary,12:00–02:00,All opening hours,1000,Zuma,Thursday Friday Saturday,Yes,Black Cod Miso,Yes,8,8,7,No,No,Indoor,Yes,Smart Elegant,Yes,Global modern Japanese institution with consistent excellence,Black cod marinated in sweet white miso grilled until caramelised,
81,Raspoutine,https://maps.app.goo.gl/5sFqm6dkpYBJ3ATS8,https://drive.google.com/file/d/1aoXdMPzid4qRyhKIdwYLIlWMxwGLMs/view?usp=sharing,https://drive.google.com/file/d/1ZwfS2Jm2mS2MATZufAzvPSXGasIkxO--/view?usp=sharing,042725373,,,Nightclub,DIFC,10% Thursdays Only / over 10k - 10% over 30k Friday,No,French,21:00 - 04:00,All opening hours,1000,"Raspoutine,Friday",,"Truffle Pasta, Beef Stroganoff, Salmon Gravlax","Raspoutine,Yes",10,5,10,9,"Raspoutine,No","Raspoutine,Indoor","Raspoutine,No","Raspoutine,Club Glam","Raspoutine,Yes","Raspoutine,""Parisian luxury club""","Raspoutine,Instagram / venue request,Parisian Luxury Club Dining,French starters; tartare; foie gras,Grilled lamb; duck confit; premium mains,Classic French cocktails; champagne,Parisian classics,500–900,Luxury; Party; Sophisticated,Parisian luxury club",
82,Ling Ling,https://maps.app.goo.gl/beH8sNPq4XCdcrVx8,https://drive.google.com/file/d/14vXK_QUPh2UhoQ6BtEqC3SqGJp8Z_zMJ/view?usp=sharing,,044262600,,,Restaurant,Palm Jumeirah,,,asian,21:00 - 04:00,All opening hours,500,"Ling Ling,Saturday",,Australian Lobster Pad Thai | Tea Smoked Duck Kueh Pie Tee | 24k Gold A5 Wagyu & Lobster Maki Sushi Rolls | Coconut in Paradise (dessert) | Warm Chocolate Hazelnut Moelleux (dessert),"Ling Ling,Yes",10,7,9,7,"Ling Ling,Yes","Ling Ling,Both","Ling Ling,No","Ling Ling,Smart Elegant","Ling Ling,Yes","Ling Ling,""Pan-Asian rooftop glamour""","Ling Ling,https://linglingdxb.com/menus,Pan-Asian Restaurant & Lounge,Sashimi; dim sum; tuna tartare,Black cod miso; wagyu gyoza; grilled prawns,Asian-inspired cocktails; sake,Black cod miso & dim sum,350–650,Seafood; Vegetarian; GF options,Rooftop Pan-Asian glamour",
76,Pacha Icons,https://maps.app.goo.gl/oM5zxDYuAjfuw3YZA,https://drive.google.com/file/d/1BHQPCozErepPQ1ERxhHg26Ed90zRpE2L/view?usp=sharing,,044559989,,,Nightclub,FIVE Luxe,10% above 3K min net spend,No,N/A,21:00 - 04:00,All opening hours,500,"Pacha Icons,Friday",,N/A (event/party series — no stable food menu),"Pacha Icons,Yes",10,5,10,7,"Pacha Icons,Yes","Pacha Icons,Outdoor","Pacha Icons,No","Pacha Icons,Club Glam","Pacha Icons,Yes","Pacha Icons,""Iconic Ibiza-style nightlife""","Pacha Icons,Instagram / venue request,Ibiza-Style Club Dining & Nightlife,Sushi rolls; sharing platters; meze,Asian fusion mains; grilled meats; fish,High-energy cocktails; club signature drinks,Sushi & sharing boards,300–600,Seafood; Party focused,Ibiza-style nightlife",
77,Terra Solis,https://maps.app.goo.gl/dhwhDPdLt5AdS9Fw9,https://drive.google.com/file/d/1H4mbrApfynRaXb7n7kvJ-3jiHqi5qQqz/view?usp=sharing,https://drive.google.com/file/d/1E45-qRiO35xP8lEnzK-1FQqIIirSOjC5/view?usp=sharing,0445598300,,,Nightclub,Dubai Heritage,10%,No,International,21:00 - 04:00,All opening hours,200,"Terra Solis,Saturday",,"Burrata (heirloom tomato, peach, molasses) | Wagyu Carpaccio (truffle ponzu) | Chilean Sea Bass (miso) | Black Angus Filet Mignon (peppercorn sauce) | Strawberry Cheesecake | Coconut Crème Brûlée","Terra Solis,No",10,5,10,7,"Terra Solis,Yes","Terra Solis,Outdoor","Terra Solis,No","Terra Solis,Resort Casual","Terra Solis,Yes","Terra Solis,""Desert festival oasis""","Terra Solis,Instagram / venue request,Desert Lounge & Dining,Gourmet salads; mezze boards,Steaks; grilled seafood; fusion mains,Crafted cocktails; signature mixes,Grilled steak & mezze,350–600,Vegetarian; Seafood,Desert festival oasis",
78,Avenue Club Dubai,https://maps.app.goo.gl/6rYEPoM4STP4Vjtj7,https://drive.google.com/file/d/10TpZ1Yxpt7o-9JYfIqfJxTtmYJ6el0Bg/view?usp=sharing,,052 781 2222,,,Nightclub,SZR,10%,No,N/A,21:00 - 04:00,All opening hours,500,"Avenue,Friday",25%,Dubai Sunset (signature cocktail) | Avenue Mojito (signature cocktail) | Chocolate Lava Cake,"Avenue,Yes",10,5,10,5,"Avenue,No","Avenue,Indoor","Avenue,No","Avenue,Club Glam","Avenue,Yes","Avenue,""Superclub nightlife energy""","Avenue,Instagram / venue request,Superclub Dining & Nightlife,Tapas; sharers; sushi,Premium grilled mains; steaks; seafood,Signature club cocktails,Tapas & signature mains,300–700,Party focused; Late night,Superclub energy",
79,Opal Room,https://maps.app.goo.gl/25j2CSwE7w9kF9d68,https://drive.google.com/file/d/1G0szD455VlYvGyntaV0PfQR9As3kgG-B/view?usp=sharing,,0542240189,,,Nightclub,DIFC,10%,No,N/A,21:00 - 04:00,All opening hours,500,"Opal Room,Friday",,Opal Fashioned | Opal Spritz | Opal‑oma | Lychee Martini | Black Orchid,"Opal Room,Yes",7,5,6,5,"Opal Room,No","Opal Room,Indoor","Opal Room,No","Opal Room,Club Glam","Opal Room,Yes","Opal Room,""Exclusive high-end clubbing""","Opal Room,Instagram / venue request,Exclusive Lounge & Club Dining,Caviar; fine appetizers; sharers,Pasta; grilled fish; premium meats,Champagne; luxury cocktails,Premium sharers & mains,500–900,Luxury; Party focused,Exclusive high-end club",
80,Ora,https://maps.app.goo.gl/KQsrvQ6trVZyj6we8,https://drive.google.com/file/d/1tRWA11buNNnFX5Ac33civgbNpk0b1crm/view?usp=sharing,,0544555115,,,Nightclub,Business Bay,10%,No,N/A,21:00 - 04:00,All opening hours,500,"Ora,Friday",,Shisha | Spring Rolls | Burger | Drinks/Juices (top dishes),"Ora,Yes",,5,6,5,"Ora,No","Ora,Indoor","Ora,No","Ora,Club Glam","Ora,Yes","Ora,""Immersive nightlife performance""","Ora,Instagram / venue request,Immersive Nightlife & Dinner,Sushi; sashimi; sharers,Asian fusion mains; duck; seafood,Curated cocktails; his spirits,Sushi & duck dishes,400–800,Party; Seafood; GF options,Immersive nightlife performance",
83,Iris,https://maps.app.goo.gl/MbC3QmFQ899EdZqh6,https://drive.google.com/file/d/19-nefGXKaOK0-WpFB34HrGPWR5ElJOG8/view?usp=sharing,,043343355,,,Nightclub,Meydan,,,,8 PM–4 AM,All opening hours,,"Iris,Friday",,,"Iris,Yes",10,5,10,7,"Iris,Yes","Iris,Outdoor","Iris,Yes","Iris,Smart Casual","Iris,Yes","Iris,""Sunset lounge & cocktails""","Iris,Instagram / venue request,Skyline Lounge & Restaurant,Small plates; mezze boards,Steak; seafood pasta; risotto,Champagne; signature cocktails,Seafood pasta & steak,450–800,Vegetarian; Seafood; GF options,Sunset lounge vibes",
84,Blu,https://maps.app.goo.gl/iYmi9x5pobcDr6Ej8,https://drive.google.com/file/d/18_S6ZW8QrtZ7k0NWVwVlyfaJqGsbdfw7/view?usp=sharing,,0521327981,,,Nightclub,Al Habtoor,,,,10 PM–4 AM,All opening hours,,"Blu,Friday",,,"Blu,Yes",10,5,10,6,"Blu,No","Blu,Indoor","Blu,No","Blu,Club Glam","Blu,Yes","Blu,""High-energy megaclub""","Blu,Instagram / venue request,High-Energy Nightclub Bites,Light sharers; finger food,Club-style mains; burgers; grilled meats,Party cocktails; bottle service,Burgers & sharers,250–500,Party; Casual,High-energy megaclub",
85,Armani prive,https://maps.app.goo.gl/SZDWUCBShAUFbc157,https://drive.google.com/file/d/1d9wxrhCWlKrUlMHCzy7iLycqzktxj1E3/view?usp=sharing,https://drive.google.com/file/d/1Q4KrmTYIkuyIdz8dQOElENi8eFf544TL/view?usp=sharing,0521769420,,,Nightclub,Downtown,,,,11 PM–3 AM,All opening hours,,"Armani prive,Friday",,,"Armani prive,Yes",10,5,10,6,"Armani prive,No","Armani prive,Indoor","Armani prive,No","Armani prive,Club Glam","Armani prive,Yes","Armani prive,""Luxury curated clubbing""","Armani Prive,Instagram / venue request,Ultra-Luxury Club Dining,Premium appetizers; ceviche,Steak; seafood medallions; risotto,Champagne; ultra-premium cocktails,Premium steak & sushi,600–1200,Luxury; Party,Luxury Armani lounge",
86,1 oak,https://maps.app.goo.gl/v4DM7JwG3VFDT2kQ7,https://drive.google.com/file/d/1RgLqyHs6xJJ7qR0chiXKFqznlnvMfMtw/view?usp=share_link,,0528818888,,,Nightclub,Downtown,,,,11 PM–3 AM,All opening hours,,"1 oak,Friday",,,"1 oak,Yes",10,5,10,6,"1 oak,No","1 oak,Indoor","1 oak,No","1 oak,Club Glam","1 oak,Yes","1 oak,""Celebrity nightlife brand""","1 OAK,Instagram / venue request,Celebrity Nightclub Dining,Nigiri; sliders; sharers,Steak tartare; premium mains,Sophisticated cocktails; champagne,Sliders & steak tartare,300–700,Party; Casual-Upscale,Celebrity brand lounge",
87,Soho garden,https://maps.app.goo.gl/etPcjZk6qa5xm2bJA,https://drive.google.com/file/d/1E_vMtDcudyOgkTq3JAMR3RwxKYi_wwk8/view?usp=sharing,,0567933366,,,Nightclub,Meydan,,,,10 PM–4 AM,All opening hours,,"Soho garden,Friday",,,"Soho garden,Yes",10,5,10,8,"Soho garden,No","Soho garden,Both","Soho garden,No","Soho garden,Club Glam","Soho garden,Yes","Soho garden,""Massive multi-zone nightlife""","Soho Garden,https://sohogardendxb.com/menus,Multi-Zone Nightlife & Dining,Flatbreads; mezze; sharers,Sushi; pasta; burgers; grilled mains,Extensive cocktail list & pitchers,Sushi & sharing platters,250–600,Party; Vegetarian options,Massive multi-zone club",
88,Vnyl,https://maps.app.goo.gl/JtTu5yus5n59vk2S7,https://drive.google.com/file/d/1PlQ4SGr33GnftN6_DvJUEwlMfPqf5vgx/view?usp=sharing,,,Nightclub,Bluewaters,,,,10 PM–4 AM,All opening hours,,"Vnyl,Friday",,,"Vnyl,Yes",10,5,10,6,"Vnyl,No","Vnyl,Indoor","Vnyl,No","Vnyl,Club Glam","Vnyl,Yes","Vnyl,""American-style party bar""","Vnyl,Instagram / venue request,American Party Bar & Lounge,Bar snacks; sharers; sliders,Burgers; casual mains; finger food,Highballs; party cocktails,Burgers & sharers,200–400,Party; Casual,American party bar",
89,Barasti,https://maps.app.goo.gl/uP2c2dTPgNKVTvJt7,https://drive.google.com/file/d/1TddJ5KTkGAbzjFC6QeKzx4OFi96GrhGp/view?usp=sharing,,045117373,,,Nightclub,Marina,,,,9 AM–3 AM,All opening hours,,"Barasti,Saturday",,,"Barasti,Yes",10,5,10,5,"Barasti,Yes","Barasti,Outdoor","Barasti,No","Barasti,Casual","Barasti,Yes","Barasti,""Casual beachfront party bar""","Barasti,Instagram / venue request,Casual Beach Bar & Grill,Nachos; wings; salads,Grilled meats; burgers; pub classics,Beer; frozen cocktails; beach drinks,Burgers & grills,150–350,Casual; Seafood; Bar food,Casual beachfront party",
90,Be beach,https://maps.app.goo.gl/svLs9o1hGRpwLqZ1A,https://drive.google.com/file/d/10GSDwlDR_r5p7x1QN_U2QQjZbhoK6Ahh/view?usp=sharing,,0547511119,,,Nightclub,Marina,,,,10 AM–7 PM,All opening hours,,"Be beach,Saturday",,,"Be beach,Yes",10,5,10,7,"Be beach,Yes","Be beach,Outdoor","Be beach,No","Be beach,Beach Chic","Be beach,Yes","Be beach,""Modern beach lounge""","Be Beach,Instagram / venue request,Modern Beach Club Dining,Sushi; light seafood starters,Grilled fish; premium meats; sharing platters,Signature cocktails; champagne,Sushi & seafood,300–550,Seafood; Vegetarian; Party focused,Modern beach lounge",
91,Wet deck,https://maps.app.goo.gl/e2GMaEHNaxmKBFjY7,https://drive.google.com/file/d/1R--Wv1Um1eHuiKks-HldsIHkEWBAFvlH/view?usp=sharing,,0547511119,,,Nightclub,Palm Jumeirah,,,,10 AM–7 PM,All opening hours,,"Wet deck,Saturday",,,"Wet deck,Yes",8,5,10,6,"Wet deck,Yes","Wet deck,Outdoor","Wet deck,No","Wet deck,Beach Club Glam","Wet deck,Yes","Wet deck,""Poolside daytime party vibes""","Wet Deck,Instagram / venue request,Poolside International Lounge,Small plates; tacos; salads,Grilled mains; seafood; burgers,Frozen cocktails; signature spritz,Poolside sharing dishes,300–600,Vegetarian; Seafood; Party focused,Poolside party vibes",
92,Bla bla,https://maps.app.goo.gl/2RgQjaMEpKCKDsDH6,https://drive.google.com/file/d/12XI38TztyrMhr8frhcgMYri4BgigIo3b/view?usp=sharing,,045844111,,,Nightclub,Jbr,,,,10 AM–3 AM,All opening hours,,"Bla bla,Saturday",,,"Bla bla,Yes",8,5,10,6,"Bla bla,Yes","Bla bla,Both","Bla bla,No","Bla bla,Casual","Bla bla,Yes","Bla bla,""Multiple concepts under one roof""","Bla Bla,Instagram / venue request,Multi-Concept Bar & Dining,Street food bites; sharers,International casual mains; grills,Wide cocktail list; beer; shots,Sharing plates,200–400,Casual; Party focused,Multi-concept party hub",
93,Amor by salvaje,https://maps.app.goo.gl/LyQ5pJDcZaweBqa9A,https://drive.google.com/file/d/1Vfb_Rg_ILDESz5cqWbQT5rIRTJ7aYOki/view?usp=sharing,,0526971356,,,Nightclub,Downtown,,,,12–3 AM,All opening hours,,"Amor by salvaje,Friday",,,"Amor by salvaje,Yes",10,6,10,7,"Amor by salvaje,Yes","Amor by salvaje,Both","Amor by salvaje,No","Amor by salvaje,Smart Elegant","Amor by salvaje,Yes","Amor by salvaje,""Dinner show with Latin flair""","Amor by Salvaje,Instagram / venue request,Latin-Japanese Dinner Show,Sharing starters; sushi; ceviche,Grilled meats; seafood; fusion mains,Show-style cocktails,Sushi & dinner show dishes,400–700,Seafood; Party focused,Latin dinner show",
94,Soho Garden The Palm,https://maps.app.goo.gl/zPKNdvUkPPGKPF9fA,https://drive.google.com/file/d/1IUykg84iodNX3oBpsys1Kc6YcERNfEjv/view?usp=sharing,,0542335555,,,Nightclub,Palm Jumeirah,,,,12 PM–2 AM,All opening hours,,"Soho Garden The Palm,Friday",,,"Soho Garden The Palm,Yes",10,5,10,7,"Soho Garden The Palm,Yes","Soho Garden The Palm,Outdoor","Soho Garden The Palm,No","Soho Garden The Palm,Club Glam","Soho Garden The Palm,Yes","Soho Garden The Palm,""Palm-side nightlife hub""","Soho Garden The Palm,Instagram / venue request,Nightlife Dining & Lounge,Flatbreads; mezze; sharers,Grilled mains; pasta; sushi,Cocktails; bottle service,Sushi & sharers,250–600,Party; Casual,Palm-side nightlife hub",
95,Beach by FIVE,https://maps.app.goo.gl/p9YGP7H7swTbB7qv9,https://drive.google.com/file/d/1Ay2m70lG3lMrUhssYWB0Ia-RaDrhZAsa/view?usp=sharing,,044559989,,,Nightclub,Palm Jumeirah,10% above 3K min net spend,No,International,12:00 - 02:00,All opening hours,,"Beach by FIVE,Saturday",25%,"Beach by FIVE,""Signature Sushi Platter | Wagyu Tacos""","Beach by FIVE,Yes",10,5,10,6,"Beach by FIVE,Yes","Beach by FIVE,Outdoor","Beach by FIVE,No","Beach by FIVE,Beach Club Glam","Beach by FIVE,Yes","Beach by FIVE,""High-energy beachfront party spot""","Beach by FIVE,Instagram / venue request,High-Energy Beach Club Dining,Light bites; sushi; sharers,Grilled meats; seafood; beach mains,Signature FIVE cocktails,Sushi & beach sharers,300–600,Party; Seafood; Vegetarian,High-energy beach party",
96,Bohemia,https://maps.app.goo.gl/jpjpezxGyNgZUMyS7,https://drive.google.com/file/d/1wyKjmEs4h-jfhj86emniDzAHYz024CXU/view?usp=sharing,,0581026643,,,Nightclub,Palm Jumeirah,10% above 3K min net spend,No,N/A,12:00 - 02:00,All opening hours,,"Bohemia,Saturday",,"Bohemia,""Lobster Rolls | Truffle Flatbread""","Bohemia,Yes",10,5,10,6,"Bohemia,Yes","Bohemia,Outdoor","Bohemia,No","Bohemia,Beach Chic","Bohemia,Yes","Bohemia,""Boho-chic beach dining""","Bohemia,Instagram / venue request,Boho-Chic Beach Dining,Salads; seafood starters,Grilled fish; Mediterranean mains,Citrus cocktails; wine,Seafood & light mains,250–450,Vegetarian; Seafood,Boho-chic beachfront",
97,Playa Pacha,https://maps.app.goo.gl/ZaZWyu6258ZfpiNB8,https://drive.google.com/file/d/1pjapje6fnjzYvbHF8ThELhx7LjVv3wkg/view?usp=sharing,https://drive.google.com/file/d/15NRDWxsdsDzSrkB-aUwIqRB_qVQ8sTIt/view?usp=sharing,044559989,,,Nightclub,Jumeirah 1,10% above 3K min net spend,No,N/A,12:00 - 02:00,All opening hours,,"Playa Pacha,Saturday",25%,"Playa Pacha,""Mediterranean Meze | Grilled Octopus""","Playa Pacha,Yes",10,5,10,8,"Playa Pacha,Yes","Playa Pacha,Outdoor","Playa Pacha,No","Playa Pacha,Beach Chic","Playa Pacha,Yes","Playa Pacha,""Ibiza-style beach dining""","Playa Pacha,Instagram / venue request,Ibiza-Style Beach Dining,Sharing starters; salads,Grilled meats; seafood; pasta,Cocktails; Ibiza-style mixes,Sharing mains,300–550,Vegetarian; Seafood,Ibiza-style beach vibes",
98,Pool by FIVE,https://maps.app.goo.gl/agNWPpLVcPuLUB5C9,https://drive.google.com/file/d/1nJT_0eOR6K7El3Eb5aG1ItEvTTVx3FiG/view?usp=sharing,,044559989,,,Nightclub,Palm Jumeirah,10% above 3K min net spend,No,N/A,12:00 - 02:00,All opening hours,,"Pool by FIVE,Saturday",,"Pool by FIVE,""Sushi Boats | Crispy Prawn Tempura""","Pool by FIVE,Yes",10,5,10,6,"Pool by FIVE,Yes","Pool by FIVE,Outdoor","Pool by FIVE,No","Pool by FIVE,Beach Club Glam","Pool by FIVE,Yes","Pool by FIVE,""Vibrant poolside party venue""","Pool by FIVE,Instagram / venue request,Poolside Party Dining,Bar bites; light sharers,Grilled mains; burgers; seafood,High-energy cocktails; pitchers,Poolside sharers,250–500,Party; Casual,Vibrant poolside party",
99,ShanghaiMe,https://maps.app.goo.gl/1TVbrmgYzwHk6BY9A,https://drive.google.com/file/d/1We5IUMgusJc5mJL0K3VydkGtnVUYY9_X/view?usp=sharing,https://drive.google.com/file/d/1WzWdo6ueMe5wrwAsiT4i8rvmq3z8VpjM/view?usp=sharing,,Restaurant,DIFC,,,,19:00 - 00:30,All opening hours,1000,,,,,,,,,,,,,,,`;

export const MENU_ITEMS_CSV = `venue_slug,course,item,description,price_aed,dietary_tags_raw
adaline,Starters,BURRATA SALAD,Heirloom tomatoes & basil,95,Vegetarian
adaline,Starters,CEVICHE DE PEZ ESPADA,Swordfish with coriander,110,Seafood
adaline,Mains,BEEF TENDERLOIN,Truffle mash & peppercorn,320,Meat
adaline,Mains,SEABASS FILLET,Artichoke & lemon butter,245,Seafood
adaline,Desserts,TIRAMISU,Traditional Venetian recipe,75,Vegetarian
african-queen,Starters,ROYALE HERVÉ N2,Premium French oysters,290,Seafood
african-queen,Starters,FOIE GRAS TERRINE,Toasted brioche & fig,195,Meat
african-queen,Mains,LOBSTER LINGUINI,Canadian lobster & cherry tomato,235,Seafood
african-queen,Mains,DOUBLE WAGYU RIBEYE,500g grain-fed wagyu,850,Meat
alaya,Cold Starters,FATTOUSH SALAD,Levantine garden greens,58,Vegetarian
alaya,Cold Starters,MAZARA HUMMUS,Mazara prawns & chili oil,138,Seafood
alaya,Meat & Poultry,SHISH WAGYU,Striploin with molasses glaze,398,Meat
alaya,Meat & Poultry,LAMB CUTLETS,Spiced yoghurt marinade,238,Meat
amazonico,Starters,Aguachile,Prawn & sea bass ceviche,90,Seafood
amazonico,Starters,Hamachi Tiradito,Passion fruit & shiso,90,Seafood
amazonico,Mains,Arroz Chaufa,Duck fried rice with grains,140,Meat
amazonico,Al Espeto,Solomillo de Res,Black Angus tenderloin,340,Meat
amelia,Starters,TUNA TARTARE,Yuzu ginger & avocado,140,Seafood
amelia,Starters,CRISPY PRAWNS,Passion fruit honey glaze,125,Seafood
amelia,Starters,WAGYU GYOZA,Foie gras & black truffle,135,Meat
amelia,Starters,BEEF TATAKI,Truffle ponzu & crispy garlic,165,Meat
amelia,Starters,CEVICHE NIKKEI,Yellowtail with sweet potato,130,Seafood
amelia,Sushi,AMELIA ROLL,Wagyu with truffle & asparagus,155,Seafood
amelia,Sushi,ACEVICHADO ROLL,Seabass & sweet potato,110,Seafood
amelia,Sushi,DRAGON ROLL,Prawn tempura & avocado,125,Seafood
amelia,Mains,BLACK COD,Miso & sake marinated,225,Seafood
amelia,Mains,WAGYU TENDERLOIN,Grade 9+ peruvian chili,420,Meat
amelia,Mains,LOBSTER LINGUINI,Fresh bisque & tomato,340,Seafood
amelia,Mains,LAMB CHOPS,Yuzu marinated & grilled,285,Meat
amelia,Desserts,TRES LECHES,Milk cake with pineapple foam,85,Vegetarian
amelia,Desserts,CHOCOLATE FONDANT,Matcha center,75,Vegetarian
ce-la-vi,Raw Bar,NIGIRI (2 PCS),Sake / Hamachi / Otoro,85,Seafood
ce-la-vi,Raw Bar,SASHIMI (3 PCS),Premium selection,95,Seafood
ce-la-vi,Raw Bar,OYSTERS,Gillardeau with yuzu mignonette,240,Seafood
ce-la-vi,Starters,MISO SOUP,Tofu and nameko,45,Vegetarian
ce-la-vi,Starters,BURRATA,Heirloom tomato & yuzu,105,Vegetarian
ce-la-vi,Starters,TRUFFLE GYOZA,Mushroom & mountain vegetables,95,Vegetarian
ce-la-vi,Sushi,CE LA VI ROLL,King crab & avocado,120,Seafood
ce-la-vi,Sushi,SPICY TUNA ROLL,Cucumber & spicy mayo,110,Seafood
ce-la-vi,Mains,BLACK COD,Miso & bok choy,240,Seafood
ce-la-vi,Mains,WAGYU BOLOGNESE,Truffle & lobster pasta,395,Meat
ce-la-vi,Mains,SEA BASS,Charred leek & dashi,210,Seafood
ce-la-vi,Mains,RIBEYE STEAK,400g grain-fed Australian beef,450,Meat
ce-la-vi,Desserts,YUZU CHEESECAKE,Seasonal berries,65,Vegetarian
ce-la-vi,Desserts,CHOCOLATE FONDANT,Matcha ice cream,75,Vegetarian
baoli,Frit & Tempura,PRAWN TEMPURA,Baoli togarashi,120,Seafood
baoli,Mains To Share,CREAMY LOBSTER UDON,Sea urchin butter,420,Seafood
baoli,Wood Fired Wagyu,WAGYU ENTRECOTE,300g grain-fed,380,Meat
baoli,Wood Fired Wagyu,CHATEAUBRIAND,450g center cut,775,Meat
nahate,Starters,NAHATÉ CEVICHE,Hamachi with leche de tigre,140,Seafood
nahate,Starters,BURRATA RAVIOLI,Sea urchin & parmesan foam,180,Seafood
nahate,Mains,BLACK SEABASS,Yuzu butter & asparagus,170,Seafood
nahate,Mains,THE CODFATHER,Miso black cod,190,Seafood
nahate,Mains,AUSTRALIAN WAGYU,Korean mustard & soy,250,Meat
nahate,Sweets,NAHATÉ TIRAMISU,Matcha & pistachio,110,Vegetarian
sirene,Appetizers,Grilled Octopus,Fava purée & capers,135,Seafood
sirene,Appetizers,Seafood Linguine,Fresh catch pasta,245,Seafood
sirene,Main Courses,Sea Bass Fillet,Lemon butter sauce,275,Seafood
sirene,Main Courses,Lamb Cutlets,Charcoal oven finished,350,Meat
zuma,Starters,Edamame,Sea salt or spicy,35,Vegetarian
zuma,Starters,Wagyu Tataki,Truffle ponzu,185,Meat
zuma,Mains,Black Cod,Miso marinated,215,Seafood
zuma,Mains,Ribeye,Wafu sauce & garlic chips,245,Meat
zuma,Sushi,Zuma Roll,Selection of fresh seafood,110,Seafood`;
